/* ============================================================
   RCP 103 QUESTIONS — Group A (copd, asthma, abg, pleural, infectious)
   ============================================================ */
(function () {
  const additions = [
    // ---------------- COPD (10) ----------------
    {
      id: 'q-copd-01',
      topic: 'copd',
      course: 'rcp103',
      difficulty: 1,
      q: 'What is the GOLD diagnostic criterion for COPD on PFT?',
      choices: ['Pre-bronchodilator FEV1/FVC < 0.80', 'Post-bronchodilator FEV1/FVC < 0.70', 'FVC < 70% predicted', 'TLC < 80% predicted'],
      correct: 1,
      explanation: 'GOLD defines COPD as a post-bronchodilator FEV1/FVC < 0.70 — airflow limitation that is not fully reversible.',
    },
    {
      id: 'q-copd-02',
      topic: 'copd',
      course: 'rcp103',
      difficulty: 1,
      q: 'Chronic bronchitis is defined clinically as a productive cough on most days for at least...',
      choices: ['1 month in 1 year', '3 months in 2 consecutive years', '6 months in 1 year', '1 year continuously'],
      correct: 1,
      explanation: 'Chronic bronchitis: productive cough most days for ≥ 3 months in 2 consecutive years.',
    },
    {
      id: 'q-copd-03',
      topic: 'copd',
      course: 'rcp103',
      difficulty: 1,
      q: 'Which clinical picture best matches the "pink puffer"?',
      choices: ['Stocky, cyanotic, edematous, productive cough', 'Thin, barrel chest, pursed-lip breathing, well-oxygenated until late', 'Obese, sleepy, hypercapnic at baseline', 'Young woman with reversible wheeze and atopy'],
      correct: 1,
      explanation: 'Emphysema (Type A, "pink puffer") — thin/cachectic, barrel chest, pursed-lip breathing, tripod posture, oxygenated until end-stage.',
    },
    {
      id: 'q-copd-04',
      topic: 'copd',
      course: 'rcp103',
      difficulty: 1,
      q: 'A 38-year-old non-smoker has lower-lobe emphysema. Which screening test is indicated?',
      choices: ['Methacholine challenge', 'Alpha-1 antitrypsin level', 'Sweat chloride test', 'High-resolution CT for asbestosis'],
      correct: 1,
      explanation: 'Screen for α1-AT deficiency in COPD diagnosed before age 45, in non-smokers, or with lower-lobe predominant emphysema.',
    },
    {
      id: 'q-copd-05',
      topic: 'copd',
      course: 'rcp103',
      difficulty: 2,
      q: 'GOLD stage 3 (Severe) COPD corresponds to which post-bronchodilator FEV1 % predicted?',
      choices: ['≥ 80%', '50–79%', '30–49%', '< 30%'],
      correct: 2,
      explanation: 'GOLD 3 (Severe) = FEV1 30–49% predicted. GOLD 1 ≥80, GOLD 2 50–79, GOLD 4 <30.',
    },
    {
      id: 'q-copd-06',
      topic: 'copd',
      course: 'rcp103',
      difficulty: 2,
      q: 'DLCO in pure emphysema and pure chronic bronchitis, respectively, is typically:',
      choices: ['Reduced; Reduced', 'Reduced; Normal', 'Increased; Reduced', 'Normal; Increased'],
      correct: 1,
      explanation: 'DLCO is REDUCED in emphysema (loss of alveolar surface area) but usually NORMAL in pure chronic bronchitis (alveoli preserved).',
    },
    {
      id: 'q-copd-07',
      topic: 'copd',
      course: 'rcp103',
      difficulty: 2,
      q: 'Target SpO2 range when titrating supplemental oxygen in a known chronic CO2 retainer with COPD:',
      choices: ['80–85%', '88–92%', '94–98%', '> 98%'],
      correct: 1,
      explanation: 'Target SpO2 88–92% in COPD CO2-retainers — preserves hypoxic drive while preventing dangerous hypoxemia.',
    },
    {
      id: 'q-copd-08',
      topic: 'copd',
      course: 'rcp103',
      difficulty: 2,
      q: 'Which lung volume change is NOT expected in COPD?',
      choices: ['Increased TLC', 'Increased RV', 'Increased FRC', 'Increased IC'],
      correct: 3,
      explanation: 'IC and IRV are DECREASED in COPD because hyperinflation (↑RV, ↑FRC) crowds out inspiratory reserve.',
    },
    {
      id: 'q-copd-09',
      topic: 'copd',
      course: 'rcp103',
      difficulty: 3,
      q: 'The mechanism by which COPD most directly leads to cor pulmonale is:',
      choices: ['Left ventricular ischemia from hypoxemia', 'Hypoxic pulmonary vasoconstriction and capillary bed destruction → pulmonary HTN', 'Aortic stenosis from chronic acidosis', 'Bronchial artery dilation overloading the LV'],
      correct: 1,
      explanation: 'Chronic hypoxia causes hypoxic pulmonary vasoconstriction; emphysema destroys the capillary bed. Result: pulmonary HTN → RV hypertrophy → cor pulmonale.',
    },
    {
      id: 'q-copd-10',
      topic: 'copd',
      course: 'rcp103',
      difficulty: 3,
      q: 'A COPD patient has pH 7.36, PaCO2 79, HCO3 43. The most accurate interpretation is:',
      choices: ['Acute respiratory acidosis — intubate', 'Fully compensated (chronic) respiratory acidosis — baseline COPD', 'Metabolic alkalosis from diuretics', 'Mixed metabolic and respiratory alkalosis'],
      correct: 1,
      explanation: 'Near-normal pH with markedly elevated PaCO2 and HCO3 = fully compensated chronic respiratory acidosis. Do NOT correct PaCO2 to 40.',
    },

    // ---------------- ASTHMA (10) ----------------
    {
      id: 'q-asthma-01',
      topic: 'asthma',
      course: 'rcp103',
      difficulty: 1,
      q: 'In the Asthma Action Plan, the GREEN zone corresponds to a PEFR of:',
      choices: ['< 50% of personal best', '50–79% of personal best', '80–100% of personal best', 'Any value with no symptoms'],
      correct: 2,
      explanation: 'Green zone = PEFR 80–100% personal best, no symptoms, continue daily controller meds.',
    },
    {
      id: 'q-asthma-02',
      topic: 'asthma',
      course: 'rcp103',
      difficulty: 1,
      q: 'A patient with PEFR 45% personal best, severe SOB, and a rescue inhaler that is not helping is in which Asthma Action Plan zone?',
      choices: ['Green', 'Yellow', 'Red', 'Blue'],
      correct: 2,
      explanation: 'Red zone (emergency): PEFR < 50%, severe SOB, rescue inhaler not helping — use SABA, oral steroids, and call 911.',
    },
    {
      id: 'q-asthma-03',
      topic: 'asthma',
      course: 'rcp103',
      difficulty: 1,
      q: 'Reversibility of airflow obstruction on PFT — the standard cutoff after bronchodilator is FEV1 improvement of:',
      choices: ['≥ 5% or 100 mL', '≥ 12% AND ≥ 200 mL', '≥ 20% AND ≥ 400 mL', '≥ 30% only'],
      correct: 1,
      explanation: 'Asthma reversibility criterion: FEV1 improves ≥ 12% AND ≥ 200 mL post-bronchodilator.',
    },
    {
      id: 'q-asthma-04',
      topic: 'asthma',
      course: 'rcp103',
      difficulty: 1,
      q: 'Which finding during a severe asthma exacerbation suggests imminent respiratory arrest?',
      choices: ['Loud expiratory wheeze', 'Silent chest with rising PaCO2', 'PaCO2 of 28 mmHg', 'SpO2 of 96%'],
      correct: 1,
      explanation: 'Silent chest = no air movement, no wheeze. Rising PaCO2 means the patient can no longer hyperventilate to compensate. Intubate.',
    },
    {
      id: 'q-asthma-05',
      topic: 'asthma',
      course: 'rcp103',
      difficulty: 2,
      q: 'The biphasic nature of asthma is BEST explained by:',
      choices: ['Allergen exposure causes vasoconstriction only', 'Early-phase mast cell/histamine bronchospasm, then late-phase eosinophilic inflammation 4–8 hr later', 'Sympathetic overdrive only', 'Bacterial superinfection during the attack'],
      correct: 1,
      explanation: 'Early phase: IgE-mast cell degranulation → bronchospasm (minutes). Late phase: eosinophils/basophils 4–8 hr later → sustained inflammation. Why steroids are essential.',
    },
    {
      id: 'q-asthma-06',
      topic: 'asthma',
      course: 'rcp103',
      difficulty: 2,
      q: 'Airway hyperresponsiveness (AHR) differs from airway remodeling because AHR is:',
      choices: ['Permanent structural change', 'A reversible exaggerated bronchoconstrictor response to triggers', 'Caused by basement membrane fibrosis', 'Only seen in COPD'],
      correct: 1,
      explanation: 'AHR is the reversible exaggerated response driving acute attacks. Remodeling is permanent (fibrosis, smooth muscle hypertrophy) and causes fixed obstruction.',
    },
    {
      id: 'q-asthma-07',
      topic: 'asthma',
      course: 'rcp103',
      difficulty: 2,
      q: 'In a patient with normal spirometry but suspected asthma, the gold-standard confirmatory test is:',
      choices: ['Sweat chloride', 'Methacholine bronchoprovocation challenge', 'High-resolution CT', 'Sleep study'],
      correct: 1,
      explanation: 'Methacholine challenge is positive when FEV1 drops ≥ 20% — confirms airway hyperresponsiveness when baseline PFTs are normal.',
    },
    {
      id: 'q-asthma-08',
      topic: 'asthma',
      course: 'rcp103',
      difficulty: 2,
      q: 'Extrinsic (allergic) asthma is typically associated with:',
      choices: ['Adult onset, normal IgE, negative skin tests', 'Childhood onset, elevated IgE, atopic triad', 'NSAID/aspirin sensitivity', 'GERD as the primary trigger'],
      correct: 1,
      explanation: 'Extrinsic asthma: childhood onset, family history of atopy, elevated IgE, positive skin tests, eosinophilia, often with eczema and allergic rhinitis.',
    },
    {
      id: 'q-asthma-09',
      topic: 'asthma',
      course: 'rcp103',
      difficulty: 3,
      q: 'A 22-year-old in severe asthma exacerbation has had a PaCO2 trend: 26 → 35 → 44. The most appropriate interpretation is:',
      choices: ['Patient is improving — compensation is normalizing', 'Patient is fatiguing; impending respiratory failure', 'Lab error — recheck', 'Metabolic alkalosis is developing'],
      correct: 1,
      explanation: 'In acute asthma the PaCO2 should be LOW from hyperventilation. A "normalizing" or rising PaCO2 signals muscle fatigue and impending arrest.',
    },
    {
      id: 'q-asthma-10',
      topic: 'asthma',
      course: 'rcp103',
      difficulty: 3,
      q: 'Which medication class should NEVER be prescribed as monotherapy for persistent asthma due to mortality risk?',
      choices: ['Inhaled corticosteroids (ICS)', 'Long-acting beta agonists (LABA)', 'Leukotriene receptor antagonists', 'Short-acting beta agonists'],
      correct: 1,
      explanation: 'LABAs (salmeterol, formoterol) must never be used alone in asthma — they require ICS combination (Advair, Symbicort) due to increased asthma death risk as monotherapy.',
    },

    // ---------------- ABG (10) ----------------
    {
      id: 'q-abg-01',
      topic: 'abg',
      course: 'rcp103',
      difficulty: 1,
      q: 'Normal arterial pH range is:',
      choices: ['7.25–7.35', '7.35–7.45', '7.45–7.55', '7.30–7.50'],
      correct: 1,
      explanation: 'Normal arterial pH is 7.35–7.45. Below 7.35 = acidosis; above 7.45 = alkalosis.',
    },
    {
      id: 'q-abg-02',
      topic: 'abg',
      course: 'rcp103',
      difficulty: 1,
      q: 'A PaO2 of 45 mmHg represents which level of hypoxemia?',
      choices: ['Mild', 'Moderate', 'Severe', 'Normal'],
      correct: 1,
      explanation: 'Moderate hypoxemia = PaO2 40–59 mmHg. Mild 60–79, severe < 40.',
    },
    {
      id: 'q-abg-03',
      topic: 'abg',
      course: 'rcp103',
      difficulty: 1,
      q: 'Allen\'s test is considered positive (safe to proceed with radial puncture) when color returns within:',
      choices: ['1–3 seconds', '5–15 seconds', '20–30 seconds', '> 30 seconds'],
      correct: 1,
      explanation: 'Color return in 5–15 seconds = positive/normal Allen\'s test = adequate ulnar collateral flow. > 15 sec = abnormal, choose another site.',
    },
    {
      id: 'q-abg-04',
      topic: 'abg',
      course: 'rcp103',
      difficulty: 1,
      q: 'The normal anion gap is:',
      choices: ['0–4 mEq/L', '8–12 mEq/L', '15–20 mEq/L', '> 20 mEq/L'],
      correct: 1,
      explanation: 'Normal anion gap = 8–12 mEq/L. Elevated (> 12) suggests MUDPILES causes.',
    },
    {
      id: 'q-abg-05',
      topic: 'abg',
      course: 'rcp103',
      difficulty: 2,
      q: 'ABG: pH 7.52, PaCO2 28, HCO3 22. The most likely cause is:',
      choices: ['Vomiting', 'Anxiety, pain, or hypoxemia (PE/asthma)', 'COPD exacerbation', 'Diabetic ketoacidosis'],
      correct: 1,
      explanation: 'Acute respiratory alkalosis (high pH, low PaCO2, normal HCO3) — from hyperventilation: anxiety, pain, hypoxemia, PE, sepsis, salicylates early.',
    },
    {
      id: 'q-abg-06',
      topic: 'abg',
      course: 'rcp103',
      difficulty: 2,
      q: 'Which condition is NOT part of the MUDPILES mnemonic for elevated anion gap metabolic acidosis?',
      choices: ['Methanol', 'Diabetic ketoacidosis', 'Diarrhea', 'Salicylates'],
      correct: 2,
      explanation: 'Diarrhea causes a NORMAL anion gap (non-gap) metabolic acidosis from bicarbonate loss. MUDPILES = Methanol, Uremia, DKA, Propylene glycol, Iron/INH, Lactic acidosis, Ethylene glycol, Salicylates.',
    },
    {
      id: 'q-abg-07',
      topic: 'abg',
      course: 'rcp103',
      difficulty: 2,
      q: 'A pH that is normal but with BOTH abnormal PaCO2 and HCO3 indicates:',
      choices: ['Uncompensated disorder', 'Partially compensated disorder', 'Fully compensated disorder', 'Mixed disorder'],
      correct: 2,
      explanation: 'Fully compensated: pH is normal, but both PaCO2 and HCO3 remain abnormal. Partially compensated still has abnormal pH.',
    },
    {
      id: 'q-abg-08',
      topic: 'abg',
      course: 'rcp103',
      difficulty: 2,
      q: 'Peripheral chemoreceptors (carotid and aortic bodies) are PRIMARILY stimulated by:',
      choices: ['Elevated PaCO2', 'Low PaO2 (< 60 mmHg)', 'High pH', 'Increased SaO2'],
      correct: 1,
      explanation: 'Peripheral chemoreceptors are the main hypoxic-drive sensors, primarily firing when PaO2 drops below ~60 mmHg. Central chemoreceptors handle CO2 mostly.',
    },
    {
      id: 'q-abg-09',
      topic: 'abg',
      course: 'rcp103',
      difficulty: 3,
      q: 'Calculate the PAO2 on room air at sea level with PaCO2 = 40 mmHg (use 0.21 × 713 – 40/0.8):',
      choices: ['~60 mmHg', '~80 mmHg', '~100 mmHg', '~150 mmHg'],
      correct: 2,
      explanation: 'PAO2 = 0.21 × (760–47) – (40/0.8) = 149.7 – 50 ≈ 100 mmHg. Normal A–a gradient = (Age/4) + 4.',
    },
    {
      id: 'q-abg-10',
      topic: 'abg',
      course: 'rcp103',
      difficulty: 3,
      q: 'ABG: pH 7.22, PaCO2 95, HCO3 38 in a known COPD patient. Best interpretation:',
      choices: ['Pure acute respiratory acidosis', 'Acute-on-chronic respiratory acidosis', 'Compensated metabolic alkalosis', 'Mixed respiratory and metabolic acidosis'],
      correct: 1,
      explanation: 'Chronic COPD baseline = elevated HCO3 (38). The acute CO2 spike to 95 dropped pH to 7.22 = acute-on-chronic respiratory acidosis. Tx: BiPAP, bronchodilators, steroids, abx.',
    },

    // ---------------- PLEURAL (10) ----------------
    {
      id: 'q-pleural-01',
      topic: 'pleural',
      course: 'rcp103',
      difficulty: 1,
      q: 'The earliest CXR sign of a pleural effusion is:',
      choices: ['Tracheal deviation toward the effusion', 'Blunting of the costophrenic angle', 'Air bronchograms', 'Kerley B lines'],
      correct: 1,
      explanation: 'Blunting of the costophrenic angle is the earliest sign of pleural effusion on a PA upright film (needs > 200–300 mL).',
    },
    {
      id: 'q-pleural-02',
      topic: 'pleural',
      course: 'rcp103',
      difficulty: 1,
      q: 'A young, tall, thin male presents with sudden chest pain and dyspnea. Breath sounds are absent on the right with hyperresonance to percussion. Most likely diagnosis:',
      choices: ['Lobar pneumonia', 'Primary spontaneous pneumothorax', 'Pleural effusion', 'Pulmonary embolism'],
      correct: 1,
      explanation: 'Classic primary spontaneous pneumothorax — tall thin young males with subpleural blebs. Absent breath sounds + hyperresonance on affected side.',
    },
    {
      id: 'q-pleural-03',
      topic: 'pleural',
      course: 'rcp103',
      difficulty: 1,
      q: 'Empyema is defined as:',
      choices: ['Air in the pleural space', 'Pus in the pleural space', 'Blood in the pleural space', 'Chyle in the pleural space'],
      correct: 1,
      explanation: 'Empyema = pus (infected fluid) in the pleural space, usually from a parapneumonic effusion. Treat with chest tube drainage + IV antibiotics.',
    },
    {
      id: 'q-pleural-04',
      topic: 'pleural',
      course: 'rcp103',
      difficulty: 1,
      q: 'A tension pneumothorax causes which tracheal finding?',
      choices: ['Tracheal deviation TOWARD the affected side', 'Tracheal deviation AWAY from the affected side', 'No tracheal deviation', 'Tracheal stenosis'],
      correct: 1,
      explanation: 'Tension PTX: rising intrathoracic pressure pushes the mediastinum AWAY from the affected side. Atelectasis pulls the trachea TOWARD.',
    },
    {
      id: 'q-pleural-05',
      topic: 'pleural',
      course: 'rcp103',
      difficulty: 2,
      q: 'First-line emergency treatment of a tension pneumothorax is:',
      choices: ['Order a stat CXR before doing anything', 'Needle decompression at the 2nd ICS midclavicular line', 'IV antibiotics', 'BiPAP'],
      correct: 1,
      explanation: 'Tension PTX is a CLINICAL diagnosis — needle decompression immediately at 2nd ICS midclavicular line (or 4th–5th ICS anterior axillary), then chest tube.',
    },
    {
      id: 'q-pleural-06',
      topic: 'pleural',
      course: 'rcp103',
      difficulty: 2,
      q: 'Which finding on pleural fluid analysis indicates an EXUDATE by Light\'s criteria?',
      choices: ['Pleural fluid protein/serum protein ratio > 0.5', 'pH > 7.4', 'Clear, straw-colored fluid', 'Glucose > 100'],
      correct: 0,
      explanation: 'Light\'s criteria for exudate: fluid/serum protein > 0.5, OR fluid/serum LDH > 0.6, OR fluid LDH > 2/3 ULN serum LDH. Any one positive = exudate.',
    },
    {
      id: 'q-pleural-07',
      topic: 'pleural',
      course: 'rcp103',
      difficulty: 2,
      q: 'Flail chest is defined as:',
      choices: ['A single rib fracture with displacement', 'Two or more adjacent ribs broken in two or more places creating a free-floating segment', 'Sternal fracture only', 'A pulmonary contusion'],
      correct: 1,
      explanation: 'Flail chest: ≥ 2 adjacent ribs broken in ≥ 2 places → free-floating segment that moves PARADOXICALLY (in on inspiration, out on expiration).',
    },
    {
      id: 'q-pleural-08',
      topic: 'pleural',
      course: 'rcp103',
      difficulty: 2,
      q: 'A patient with CHF develops a pleural effusion. The fluid is most likely:',
      choices: ['Exudate from increased capillary permeability', 'Transudate from increased hydrostatic pressure', 'Pus from bacterial infection', 'Chyle from thoracic duct injury'],
      correct: 1,
      explanation: 'Heart failure, cirrhosis, and nephrotic syndrome produce TRANSUDATES (high hydrostatic or low oncotic pressure). Clear, low-protein fluid.',
    },
    {
      id: 'q-pleural-09',
      topic: 'pleural',
      course: 'rcp103',
      difficulty: 3,
      q: 'The mechanism by which a tension pneumothorax causes hemodynamic collapse is:',
      choices: ['Direct compression of the LV myocardium', 'Mediastinal shift kinks the great vessels → ↓ venous return → ↓ cardiac output (obstructive shock)', 'Pulmonary embolism in the PA', 'Massive pleural fluid pressing on the diaphragm'],
      correct: 1,
      explanation: 'Rising intrathoracic pressure shifts the mediastinum, kinking the SVC and great vessels → ↓ preload → ↓ stroke volume → obstructive shock.',
    },
    {
      id: 'q-pleural-10',
      topic: 'pleural',
      course: 'rcp103',
      difficulty: 3,
      q: 'A flail chest segment moves which direction on inspiration?',
      choices: ['OUT (with the rest of the chest)', 'IN (paradoxical — opposite to the rest of the chest)', 'Does not move', 'Rotates'],
      correct: 1,
      explanation: 'On inspiration, negative intrathoracic pressure sucks the unattached flail segment IN while the rest of the chest moves OUT — paradoxical movement.',
    },

    // ---------------- INFECTIOUS (10) ----------------
    {
      id: 'q-infectious-01',
      topic: 'infectious',
      course: 'rcp103',
      difficulty: 1,
      q: 'Ventilator-associated pneumonia (VAP) is defined as pneumonia developing after intubation for:',
      choices: ['> 12 hours', '> 24 hours', '> 48 hours', '> 1 week'],
      correct: 2,
      explanation: 'VAP = pneumonia > 48 hr after intubation. HAP = > 48 hr after hospital admission. CAP = onset in the community.',
    },
    {
      id: 'q-infectious-02',
      topic: 'infectious',
      course: 'rcp103',
      difficulty: 1,
      q: 'Lobar pneumonia with homogeneous consolidation of an entire lobe and air bronchograms is classic for:',
      choices: ['Staphylococcus aureus', 'Streptococcus pneumoniae', 'Mycoplasma pneumoniae', 'Pneumocystis jirovecii'],
      correct: 1,
      explanation: 'Streptococcus pneumoniae classically causes lobar pneumonia (homogeneous lobar consolidation + air bronchograms). Staph/Pseudomonas = bronchopneumonia (patchy).',
    },
    {
      id: 'q-infectious-03',
      topic: 'infectious',
      course: 'rcp103',
      difficulty: 1,
      q: 'Histoplasmosis is most strongly associated with which exposure?',
      choices: ['Pigeon droppings', 'Bat guano and bird (chicken/starling) droppings in Mississippi/Ohio valleys', 'Southwestern desert soil/dust', 'Moldy hay'],
      correct: 1,
      explanation: 'Histoplasma capsulatum — bat and bird droppings, endemic to Mississippi and Ohio River valleys. Pigeon = Cryptococcus; SW dust = Coccidioides; hay = farmer\'s lung.',
    },
    {
      id: 'q-infectious-04',
      topic: 'infectious',
      course: 'rcp103',
      difficulty: 1,
      q: 'A TB skin test (PPD) should be read at:',
      choices: ['Immediately', '12–24 hours', '48–72 hours', '1 week'],
      correct: 2,
      explanation: 'PPD is read at 48–72 hours. Measure INDURATION (raised area), not redness.',
    },
    {
      id: 'q-infectious-05',
      topic: 'infectious',
      course: 'rcp103',
      difficulty: 2,
      q: 'A PPD of 8 mm induration is considered POSITIVE in which patient?',
      choices: ['Healthy adult with no risk factors', 'Recent immigrant from a high-prevalence country', 'Newborn with no exposures', 'Adult with seasonal allergies'],
      correct: 1,
      explanation: '≥10 mm cutoff: recent immigrants, IV drug users, healthcare workers, congregate-setting residents, children <4, DM, silicosis, CKD. ≥15 mm for everyone else.',
    },
    {
      id: 'q-infectious-06',
      topic: 'infectious',
      course: 'rcp103',
      difficulty: 2,
      q: 'The isolation precaution required for active TB is:',
      choices: ['Standard precautions only', 'Contact precautions', 'Droplet precautions', 'Airborne precautions — negative-pressure room and N95 respirator'],
      correct: 3,
      explanation: 'Active TB requires AIRBORNE precautions: negative-pressure room and N95 respirator. The organism remains suspended in air droplet nuclei.',
    },
    {
      id: 'q-infectious-07',
      topic: 'infectious',
      course: 'rcp103',
      difficulty: 2,
      q: 'Cryptococcus neoformans is most strongly associated with which exposure and complication?',
      choices: ['Bat caves; cavitary lesions', 'Pigeon droppings; meningitis in AIDS patients', 'SW desert soil; valley fever', 'Decaying wood; aspergilloma'],
      correct: 1,
      explanation: 'Cryptococcus = pigeon droppings (worldwide). In AIDS patients, pulmonary infection disseminates to MENINGITIS — classic high-yield association.',
    },
    {
      id: 'q-infectious-08',
      topic: 'infectious',
      course: 'rcp103',
      difficulty: 2,
      q: 'A sputum sample is considered valid for Gram stain when it has:',
      choices: ['> 25 epithelial cells per LPF', '> 25 WBC and < 10 epithelial cells per LPF', 'Pure saliva', 'Equal numbers of WBC and epithelial cells'],
      correct: 1,
      explanation: 'Valid lower respiratory sample: > 25 WBC AND < 10 epithelial cells per low-power field. High epithelial cell counts = upper airway contamination.',
    },
    {
      id: 'q-infectious-09',
      topic: 'infectious',
      course: 'rcp103',
      difficulty: 3,
      q: 'An HIV+ patient with CD4 count of 150 presents with progressive dyspnea and diffuse bilateral interstitial "ground-glass" infiltrates on CXR. Best initial empiric therapy:',
      choices: ['Amphotericin B', 'TMP-SMX (Bactrim)', 'Vancomycin', 'Isoniazid + rifampin'],
      correct: 1,
      explanation: 'Pneumocystis jirovecii pneumonia (PCP) — opportunistic in HIV with CD4 < 200, diffuse ground-glass infiltrates. First-line: TMP-SMX; alternative pentamidine.',
    },
    {
      id: 'q-infectious-10',
      topic: 'infectious',
      course: 'rcp103',
      difficulty: 3,
      q: 'The GOLD STANDARD test for confirming active pulmonary TB is:',
      choices: ['PPD skin test', 'Chest X-ray', 'AFB smear', 'Sputum culture for Mycobacterium tuberculosis'],
      correct: 3,
      explanation: 'Sputum CULTURE remains the gold standard (takes 2–8 weeks). AFB smear is faster but less sensitive; NAAT/GeneXpert is rapid. PPD only shows exposure.',
    },
  ];
  // Replace any prior rcp103 questions with topic in this group, keep others
  const groupTopics = ['copd','asthma','abg','pleural','infectious'];
  const existing = (window.ALL_QUESTIONS || []).filter(q => !(q.course === 'rcp103' && groupTopics.includes(q.topic)));
  window.ALL_QUESTIONS = existing.concat(additions);
})();
