/* ============================================================
   RCP 104 QUESTIONS — Group A (Chapters 11–16)
   ============================================================ */
(function () {
  const additions = [
    /* ---------- Ch 11 · Corticosteroids (10) ---------- */
    {
      id: 'q-cort-01',
      topic: 'corticosteroids',
      course: 'rcp104',
      difficulty: 1,
      q: "Pulmicort's generic name is?",
      choices: ['Fluticasone','Budesonide','Beclomethasone','Mometasone'],
      correct: 1,
      explanation: 'Pulmicort = budesonide (ICS available as Flexhaler DPI and Respules SVN).',
    },
    {
      id: 'q-cort-02',
      topic: 'corticosteroids',
      course: 'rcp104',
      difficulty: 1,
      q: "Flovent's generic name is?",
      choices: ['Fluticasone propionate','Budesonide','Ciclesonide','Flunisolide'],
      correct: 0,
      explanation: 'Flovent HFA/Diskus = fluticasone propionate.',
    },
    {
      id: 'q-cort-03',
      topic: 'corticosteroids',
      course: 'rcp104',
      difficulty: 1,
      q: 'Which combination drug pairs fluticasone with salmeterol?',
      choices: ['Symbicort','Dulera','Advair','Breo Ellipta'],
      correct: 2,
      explanation: 'Advair = fluticasone propionate + salmeterol (ICS/LABA).',
    },
    {
      id: 'q-cort-04',
      topic: 'corticosteroids',
      course: 'rcp104',
      difficulty: 2,
      q: 'Symbicort is the combination of which two drugs?',
      choices: ['Fluticasone + salmeterol','Budesonide + formoterol','Mometasone + formoterol','Fluticasone + vilanterol'],
      correct: 1,
      explanation: 'Symbicort = budesonide + formoterol fumarate (HFA MDI).',
    },
    {
      id: 'q-cort-05',
      topic: 'corticosteroids',
      course: 'rcp104',
      difficulty: 2,
      q: 'Endogenous glucocorticoid (cortisol) secretion follows what type of rhythm?',
      choices: ['Ultradian','Diurnal / Circadian','Infradian','Random pulsatile'],
      correct: 1,
      explanation: 'Cortisol follows a diurnal (circadian) rhythm — peak ~8 a.m.',
    },
    {
      id: 'q-cort-06',
      topic: 'corticosteroids',
      course: 'rcp104',
      difficulty: 2,
      q: 'What are the two MOST COMMON local side effects of inhaled corticosteroids?',
      choices: ['Tachycardia & tremor','Oral candidiasis (thrush) & dysphonia','HTN & hyperglycemia','Cataracts & osteoporosis'],
      correct: 1,
      explanation: 'Oropharyngeal candidiasis (thrush) and dysphonia (hoarseness) are the most common local effects. Rinse mouth after use.',
    },
    {
      id: 'q-cort-07',
      topic: 'corticosteroids',
      course: 'rcp104',
      difficulty: 2,
      q: 'Which inflammatory cell is the MAJOR effector cell of asthmatic inflammation, regardless of allergic vs non-allergic?',
      choices: ['Neutrophils','Mast cells and eosinophils','Macrophages','T-suppressor cells'],
      correct: 1,
      explanation: 'Mast cells and eosinophils are the major effector cells in asthma inflammation.',
    },
    {
      id: 'q-cort-08',
      topic: 'corticosteroids',
      course: 'rcp104',
      difficulty: 2,
      q: 'In COPD, which inflammatory cell predominates (in contrast to eosinophils in asthma)?',
      choices: ['Mast cells','Basophils','Neutrophils','T-helper cells'],
      correct: 2,
      explanation: 'Neutrophils predominate in COPD; eosinophils predominate in asthma.',
    },
    {
      id: 'q-cort-09',
      topic: 'corticosteroids',
      course: 'rcp104',
      difficulty: 3,
      q: 'Inhaled corticosteroids are classified as which type of asthma medication?',
      choices: ['Rescue / Reliever','Controller (maintenance)','Bronchodilator','Mucolytic'],
      correct: 1,
      explanation: 'ICS are CONTROLLERS for maintenance therapy — NOT a rescue agent. Not used in acute severe asthma.',
    },
    {
      id: 'q-cort-10',
      topic: 'corticosteroids',
      course: 'rcp104',
      difficulty: 3,
      q: 'A patient on long-term systemic steroids is being transitioned to inhaled. What is the major concern?',
      choices: ['Mast cell hyperplasia','HPA axis suppression / adrenal insufficiency','Rebound bronchodilation','Hyperkalemia'],
      correct: 1,
      explanation: 'Transition from systemic → inhaled may unmask adrenal insufficiency due to prior HPA suppression; weaning/tapering is required.',
    },

    /* ---------- Ch 12 · Non-Steroidal Anti-Asthma (10) ---------- */
    {
      id: 'q-nonst-01',
      topic: 'nonsteroidal',
      course: 'rcp104',
      difficulty: 1,
      q: 'Singulair (montelukast) belongs to which drug class?',
      choices: ['Mast cell stabilizer','Leukotriene receptor antagonist (LTRA)','5-LO inhibitor','Monoclonal antibody'],
      correct: 1,
      explanation: 'Montelukast (Singulair) is a CysLT1 leukotriene receptor antagonist (LTRA).',
    },
    {
      id: 'q-nonst-02',
      topic: 'nonsteroidal',
      course: 'rcp104',
      difficulty: 1,
      q: "Cromolyn sodium's primary mechanism of action is?",
      choices: ['Blocks leukotriene receptors','Mast cell stabilizer — blocks degranulation','β2 agonist bronchodilator','Anticholinergic'],
      correct: 1,
      explanation: 'Cromolyn sodium is a mast cell stabilizer that prevents degranulation; PROPHYLACTIC use only.',
    },
    {
      id: 'q-nonst-03',
      topic: 'leukotrienes',
      course: 'rcp104',
      difficulty: 2,
      q: 'Which antileukotriene is a 5-lipoxygenase (5-LO) inhibitor (blocks PRODUCTION rather than receptors)?',
      choices: ['Montelukast','Zafirlukast','Zileuton','Omalizumab'],
      correct: 2,
      explanation: 'Zileuton (Zyflo) inhibits the 5-LO enzyme, blocking leukotriene production. Liver function must be monitored.',
    },
    {
      id: 'q-nonst-04',
      topic: 'nonsteroidal',
      course: 'rcp104',
      difficulty: 1,
      q: 'Cromolyn sodium and antileukotrienes are best classified as which type of asthma agent?',
      choices: ['Reliever (rescue)','Controller (prophylactic)','β2-antagonist','Anti-infective'],
      correct: 1,
      explanation: 'They are CONTROLLERS — prophylactic. NOT indicated for acute bronchospasm.',
    },
    {
      id: 'q-nonst-05',
      topic: 'nonsteroidal',
      course: 'rcp104',
      difficulty: 2,
      q: 'Which best describes the difference between albuterol and cromolyn sodium?',
      choices: ['Both are bronchodilators','Albuterol is rescue (β2 bronchodilator); cromolyn is controller (mast cell stabilizer)','Both are mast cell stabilizers','Albuterol is steroidal; cromolyn is non-steroidal'],
      correct: 1,
      explanation: 'Albuterol = SABA reliever. Cromolyn = anti-inflammatory mast cell stabilizer used prophylactically.',
    },
    {
      id: 'q-nonst-06',
      topic: 'nonsteroidal',
      course: 'rcp104',
      difficulty: 2,
      q: 'Extrinsic asthma is best characterized as?',
      choices: ['No identifiable allergen / sensitization','Allergy-driven (atopy, IgE mediated)','Exercise-induced only','Aspirin-induced'],
      correct: 1,
      explanation: 'Extrinsic asthma is allergy/atopy-driven (IgE-mediated). Intrinsic shows no clear allergen sensitization.',
    },
    {
      id: 'q-nonst-07',
      topic: 'leukotrienes',
      course: 'rcp104',
      difficulty: 2,
      q: 'Xolair (omalizumab) works by?',
      choices: ['Blocking the CysLT1 receptor','Binding IgE to prevent mast cell attachment','Blocking IL-5','Inhibiting 5-LO'],
      correct: 1,
      explanation: 'Omalizumab (Xolair) is a monoclonal anti-IgE antibody — used in severe allergic asthma.',
    },
    {
      id: 'q-nonst-08',
      topic: 'leukotrienes',
      course: 'rcp104',
      difficulty: 3,
      q: 'Nucala (mepolizumab), Cinqair (reslizumab), and Fasenra (benralizumab) all target?',
      choices: ['IgE','Interleukin-5 (IL-5)','Histamine','Leukotrienes'],
      correct: 1,
      explanation: 'These biologics block IL-5 signaling, reducing eosinophils — used in eosinophilic asthma.',
    },
    {
      id: 'q-nonst-09',
      topic: 'nonsteroidal',
      course: 'rcp104',
      difficulty: 2,
      q: 'Which immunoglobulin is most central to the allergic asthmatic response?',
      choices: ['IgA','IgG','IgM','IgE'],
      correct: 3,
      explanation: 'IgE binds mast cells; reexposure to antigen triggers degranulation and the early-phase asthma response.',
    },
    {
      id: 'q-nonst-10',
      topic: 'leukotrienes',
      course: 'rcp104',
      difficulty: 3,
      q: 'Accolate is the trade name for which leukotriene receptor antagonist?',
      choices: ['Montelukast','Zafirlukast','Zileuton','Omalizumab'],
      correct: 1,
      explanation: 'Accolate = zafirlukast (LTRA, oral, BID dosing).',
    },

    /* ---------- Ch 13 · Anti-Infective (10) ---------- */
    {
      id: 'q-antiinf-01',
      topic: 'pentamidine',
      course: 'rcp104',
      difficulty: 1,
      q: 'Pentamidine (NebuPent) is classified as an?',
      choices: ['Antiviral','Antibiotic','Antifungal','Mucolytic'],
      correct: 2,
      explanation: 'Pentamidine is classified as an ANTIFUNGAL, used for PCP/PJP prophylaxis in AIDS patients.',
    },
    {
      id: 'q-antiinf-02',
      topic: 'pentamidine',
      course: 'rcp104',
      difficulty: 1,
      q: 'Aerosolized pentamidine is primarily indicated for?',
      choices: ['RSV bronchiolitis','PCP / PJP prophylaxis in AIDS patients','MRSA pneumonia','TB treatment'],
      correct: 1,
      explanation: 'Pentamidine = Pneumocystis jiroveci pneumonia (PJP/PCP) prophylaxis in AIDS, 300 mg every 4 weeks via Respirgard II.',
    },
    {
      id: 'q-antiinf-03',
      topic: 'ribavirin',
      course: 'rcp104',
      difficulty: 1,
      q: 'Ribavirin (Virazole) is indicated for?',
      choices: ['Pseudomonas in CF','Severe RSV in hospitalized infants','Influenza A & B','PCP prophylaxis'],
      correct: 1,
      explanation: 'Ribavirin is an antiviral used for severe lower respiratory RSV infections in hospitalized infants, via SPAG-2 nebulizer.',
    },
    {
      id: 'q-antiinf-04',
      topic: 'ribavirin',
      course: 'rcp104',
      difficulty: 2,
      q: 'Children diagnosed with RSV most commonly present with which two concurrent problems?',
      choices: ['Bronchiolitis and pneumonia','Asthma and croup','Pertussis and influenza','TB and PCP'],
      correct: 0,
      explanation: 'RSV in children causes bronchiolitis and pneumonia (PNA). Seasonal — Fall/Winter.',
    },
    {
      id: 'q-antiinf-05',
      topic: 'cf',
      course: 'rcp104',
      difficulty: 1,
      q: 'TOBI (tobramycin) is indicated for?',
      choices: ['Pneumocystis pneumonia','RSV','Chronic Pseudomonas aeruginosa in CF patients','Influenza'],
      correct: 2,
      explanation: 'Aerosolized tobramycin (TOBI) manages chronic P. aeruginosa infection in CF — 300 mg BID, 28 days on / 28 days off.',
    },
    {
      id: 'q-antiinf-06',
      topic: 'cf',
      course: 'rcp104',
      difficulty: 2,
      q: 'Aztreonam (Cayston) — what should be done BEFORE each dosing?',
      choices: ['Administer steroid','Pretreat with a bronchodilator','Suction the airway','Place patient prone'],
      correct: 1,
      explanation: 'Pretreat with a bronchodilator before each Cayston dose — it can cause bronchospasm and reduce FEV1.',
    },
    {
      id: 'q-antiinf-07',
      topic: 'antiinfective',
      course: 'rcp104',
      difficulty: 2,
      q: 'Zanamivir (Relenza) — mechanism of action?',
      choices: ['Inhibits viral RNA polymerase','Binds and inhibits the enzyme neuraminidase','Mast cell stabilizer','Bactericidal cell wall inhibitor'],
      correct: 1,
      explanation: 'Zanamivir is a neuraminidase inhibitor — used for influenza A & B (within 2 days of onset).',
    },
    {
      id: 'q-antiinf-08',
      topic: 'pentamidine',
      course: 'rcp104',
      difficulty: 2,
      q: 'Pentamidine should be reconstituted with?',
      choices: ['Normal saline','Sterile water','D5W','Albuterol solution'],
      correct: 1,
      explanation: '300 mg pentamidine vial is reconstituted with 6 mL of STERILE WATER. Saline causes precipitation.',
    },
    {
      id: 'q-antiinf-09',
      topic: 'cf',
      course: 'rcp104',
      difficulty: 3,
      q: 'Which CF medication is a recombinant DNase that cleaves extracellular DNA in mucus?',
      choices: ['Tobramycin','Dornase alfa (Pulmozyme)','Aztreonam','Ribavirin'],
      correct: 1,
      explanation: 'Dornase alfa (Pulmozyme) is a mucolytic that breaks down DNA in thick CF mucus.',
    },
    {
      id: 'q-antiinf-10',
      topic: 'ribavirin',
      course: 'rcp104',
      difficulty: 3,
      q: 'Which device is REQUIRED to deliver aerosolized ribavirin?',
      choices: ['MDI with spacer','SPAG-2 (Small Particle Aerosol Generator)','Respirgard II','Ultrasonic nebulizer'],
      correct: 1,
      explanation: 'Ribavirin is delivered via SPAG-2 nebulizer, 12–18 hr/day continuous, for 3–7 days.',
    },

    /* ---------- Ch 14 · Antimicrobials (10) ---------- */
    {
      id: 'q-antimicro-01',
      topic: 'tb-meds',
      course: 'rcp104',
      difficulty: 1,
      q: 'The RIPE acronym for TB therapy stands for?',
      choices: ['Rifampin, Isoniazid, Pyrazinamide, Ethambutol','Ribavirin, INH, Penicillin, Erythromycin','Rifabutin, Imipenem, Piperacillin, Ethambutol','Rifampin, Imipenem, Pentamidine, Ertapenem'],
      correct: 0,
      explanation: 'RIPE = Rifampin, Isoniazid (INH), Pyrazinamide, Ethambutol — first-line TB therapy.',
    },
    {
      id: 'q-antimicro-02',
      topic: 'tb-meds',
      course: 'rcp104',
      difficulty: 1,
      q: 'TB is rapidly diagnosed using which type of stain?',
      choices: ['Gram stain','Acid-fast stain (AFB)','Wright stain','India ink'],
      correct: 1,
      explanation: 'Mycobacterium tuberculosis is identified by the acid-fast bacilli (AFB) stain.',
    },
    {
      id: 'q-antimicro-03',
      topic: 'antimicrobial',
      course: 'rcp104',
      difficulty: 1,
      q: 'Bactericidal vs. bacteriostatic — bactericidal means?',
      choices: ['Kills the bacteria','Prevents bacteria from growing','Stimulates immune response','Causes the bacteria to mutate'],
      correct: 0,
      explanation: 'Bactericidal = KILLS bacteria. Bacteriostatic = PREVENTS growth.',
    },
    {
      id: 'q-antimicro-04',
      topic: 'antimicrobial',
      course: 'rcp104',
      difficulty: 2,
      q: 'Vancomycin is the drug of choice for which organism?',
      choices: ['VRE','MRSA','Pseudomonas aeruginosa','Mycobacterium tuberculosis'],
      correct: 1,
      explanation: 'Vancomycin = MRSA (methicillin-resistant Staph aureus). It is INEFFECTIVE against VRE.',
    },
    {
      id: 'q-antimicro-05',
      topic: 'antimicrobial',
      course: 'rcp104',
      difficulty: 2,
      q: 'The most common adverse reaction to penicillin is?',
      choices: ['Nephrotoxicity','Hypersensitivity / allergic reaction','Ototoxicity','Hepatotoxicity'],
      correct: 1,
      explanation: 'Hypersensitivity is the most common penicillin adverse reaction; cross-reactivity exists with other β-lactams.',
    },
    {
      id: 'q-antimicro-06',
      topic: 'vap-meds',
      course: 'rcp104',
      difficulty: 2,
      q: 'Aminoglycosides (gentamicin, tobramycin) are commonly used for VAP — major adverse reactions include?',
      choices: ['Hepatotoxicity and rash','Nephrotoxicity and ototoxicity','Hypoglycemia and seizures','Bone marrow suppression and alopecia'],
      correct: 1,
      explanation: 'Aminoglycosides are notorious for nephrotoxicity and ototoxicity (auditory + vestibular).',
    },
    {
      id: 'q-antimicro-07',
      topic: 'tb-meds',
      course: 'rcp104',
      difficulty: 2,
      q: 'What type of isolation precaution is required for an active TB patient?',
      choices: ['Contact','Droplet','Airborne (negative-pressure room, N95)','Standard only'],
      correct: 2,
      explanation: 'Active TB requires AIRBORNE isolation — negative-pressure room with ≥6 air changes/hr and N95 respirator.',
    },
    {
      id: 'q-antimicro-08',
      topic: 'tb-meds',
      course: 'rcp104',
      difficulty: 3,
      q: 'Rifampin commonly causes which harmless but distinctive side effect?',
      choices: ['Blue-tinted skin','Orange-colored body fluids (urine, tears, sweat)','Black tongue','Yellow sclera'],
      correct: 1,
      explanation: 'Rifampin turns body fluids orange — counsel patients; it is harmless but staining.',
    },
    {
      id: 'q-antimicro-09',
      topic: 'antimicrobial',
      course: 'rcp104',
      difficulty: 3,
      q: 'How do most antivirals (e.g., acyclovir, oseltamivir) work?',
      choices: ['Inhibit bacterial cell wall synthesis','Interfere with viral DNA/RNA replication or release','Block β-lactamase enzyme','Stabilize mast cells'],
      correct: 1,
      explanation: 'Antivirals interfere with viral nucleic acid replication or assembly/release (e.g., neuraminidase inhibition).',
    },
    {
      id: 'q-antimicro-10',
      topic: 'vap-meds',
      course: 'rcp104',
      difficulty: 3,
      q: 'A 5th-generation cephalosporin notable for activity against MRSA is?',
      choices: ['Cefazolin','Ceftriaxone','Ceftaroline','Cefepime'],
      correct: 2,
      explanation: 'Ceftaroline is the only 5th-generation cephalosporin — has MRSA activity (but NOT P. aeruginosa).',
    },

    /* ---------- Ch 15 · Cold & Cough (10) ---------- */
    {
      id: 'q-cough-01',
      topic: 'cold-cough',
      course: 'rcp104',
      difficulty: 1,
      q: 'Diphenhydramine hydrochloride is the generic name for?',
      choices: ['Sudafed','Benadryl','Robitussin','Mucinex'],
      correct: 1,
      explanation: 'Diphenhydramine HCl = Benadryl (first-generation H1-antagonist antihistamine).',
    },
    {
      id: 'q-cough-02',
      topic: 'cold-cough',
      course: 'rcp104',
      difficulty: 1,
      q: 'The common cold is caused by what type of infection?',
      choices: ['Bacterial upper airway','Viral upper respiratory tract infection','Fungal lower airway','Parasitic'],
      correct: 1,
      explanation: 'The common cold is a NON-bacterial (viral, often rhinovirus) upper respiratory tract infection.',
    },
    {
      id: 'q-cough-03',
      topic: 'cold-cough',
      course: 'rcp104',
      difficulty: 1,
      q: 'Antihistamines cause which class of side effects due to H1 blockade?',
      choices: ['Cholinergic effects','Anticholinergic effects (dry secretions, blurred vision, urinary retention)','β-blocker effects','Sympathomimetic effects'],
      correct: 1,
      explanation: 'H1-blockers cause anticholinergic side effects: drying of secretions, blurred vision, urinary retention, constipation.',
    },
    {
      id: 'q-cough-04',
      topic: 'cold-cough',
      course: 'rcp104',
      difficulty: 2,
      q: 'Which oral decongestant is a sympathomimetic α-agonist used for nasal vasoconstriction?',
      choices: ['Loratadine','Pseudoephedrine (Sudafed)','Dextromethorphan','Guaifenesin'],
      correct: 1,
      explanation: 'Pseudoephedrine (Sudafed) is an α-adrenergic agonist causing vasoconstriction and decongestion.',
    },
    {
      id: 'q-cough-05',
      topic: 'mucolytics',
      course: 'rcp104',
      difficulty: 2,
      q: 'Guaifenesin (Robitussin / Mucinex) is which class of drug?',
      choices: ['Antitussive','Expectorant','Antihistamine','Decongestant'],
      correct: 1,
      explanation: 'Guaifenesin is an EXPECTORANT — increases mucus clearance / reduces adhesiveness and surface tension.',
    },
    {
      id: 'q-cough-06',
      topic: 'cold-cough',
      course: 'rcp104',
      difficulty: 2,
      q: 'Which is a NON-narcotic antitussive?',
      choices: ['Codeine','Hydrocodone (Vicodin)','Dextromethorphan','Morphine'],
      correct: 2,
      explanation: 'Dextromethorphan (Robitussin Max Strength) and Benzonatate (Tessalon) are non-narcotic antitussives.',
    },
    {
      id: 'q-cough-07',
      topic: 'cold-cough',
      course: 'rcp104',
      difficulty: 2,
      q: 'Cough suppressants (antitussives) work primarily by?',
      choices: ['Thinning mucus','Depressing the cough center in the medulla','Vasoconstricting nasal mucosa','Blocking H1 receptors'],
      correct: 1,
      explanation: 'Antitussives depress the cough center in the medulla.',
    },
    {
      id: 'q-cough-08',
      topic: 'cold-cough',
      course: 'rcp104',
      difficulty: 2,
      q: 'Second-generation antihistamines (loratadine, fexofenadine, cetirizine) differ from first-generation in that they?',
      choices: ['Cause more drowsiness','Do NOT cross the blood–brain barrier (non-sedating)','Have stronger anticholinergic effects','Are only available IV'],
      correct: 1,
      explanation: 'Second-generation H1-antagonists do not readily cross the BBB — non-sedating and better tolerated.',
    },
    {
      id: 'q-cough-09',
      topic: 'cold-cough',
      course: 'rcp104',
      difficulty: 3,
      q: 'Tamiflu (oseltamivir) is used to treat?',
      choices: ['Common cold (rhinovirus)','Influenza A and B','RSV','Pneumocystis pneumonia'],
      correct: 1,
      explanation: 'Oseltamivir (Tamiflu) is an oral neuraminidase inhibitor used for influenza A and B.',
    },
    {
      id: 'q-cough-10',
      topic: 'cold-cough',
      course: 'rcp104',
      difficulty: 3,
      q: 'A key teaching point about antitussives is?',
      choices: ['Use them in all coughs','Never suppress a PRODUCTIVE cough','Always combine with antibiotic','They are bronchodilators'],
      correct: 1,
      explanation: 'Antitussives are for nonproductive, irritating, dry coughs — NEVER suppress a productive cough.',
    },

    /* ---------- Ch 16 · α1-AT / Nitric Oxide / Smoking (10) ---------- */
    {
      id: 'q-emph-01',
      topic: 'emphysema-rx',
      course: 'rcp104',
      difficulty: 1,
      q: 'α1-Antitrypsin deficiency is associated with which type of emphysema?',
      choices: ['Centrilobular (upper lobes)','Panacinar / Panlobular (lower lobes)','Bullous (apical)','Paraseptal'],
      correct: 1,
      explanation: 'α1-AT deficiency → Panacinar (panlobular) emphysema, predominantly in the LOWER lobes. Centrilobular = upper lobes, smoking-related.',
    },
    {
      id: 'q-emph-02',
      topic: 'emphysema-rx',
      course: 'rcp104',
      difficulty: 1,
      q: 'Centrilobular (centriacinar) emphysema is most typically associated with?',
      choices: ['α1-AT deficiency','Cigarette smoking; primarily upper lobes','Asthma','CF'],
      correct: 1,
      explanation: 'Centrilobular emphysema = smoking, upper lobes. Panacinar (lower lobes) = α1-AT deficiency.',
    },
    {
      id: 'q-emph-03',
      topic: 'nitric-oxide',
      course: 'rcp104',
      difficulty: 2,
      q: 'Inhaled Nitric Oxide (NO) is FDA approved for?',
      choices: ['Adult ARDS','Persistent Pulmonary Hypertension of the Newborn (PPHN)','Asthma exacerbation','COPD','CF'],
      correct: 1,
      explanation: 'iNO (INOmax) is approved for PPHN in term/near-term neonates with hypoxic respiratory failure. ARDS use is off-label/investigational.',
    },
    {
      id: 'q-emph-04',
      topic: 'nitric-oxide',
      course: 'rcp104',
      difficulty: 2,
      q: 'The two TOXIC products of inhaled nitric oxide are?',
      choices: ['Carbon monoxide and CO2','Methemoglobin (MetHb) and Nitrogen Dioxide (NO2)','Sulfur dioxide and ozone','Cyanide and ammonia'],
      correct: 1,
      explanation: 'NO toxicity = Methemoglobin (from Hb binding) and Nitrogen Dioxide (NO2) when NO reacts with O2.',
    },
    {
      id: 'q-emph-05',
      topic: 'nitric-oxide',
      course: 'rcp104',
      difficulty: 2,
      q: 'Recommended starting dose of inhaled nitric oxide for PPHN is?',
      choices: ['2 ppm','5 ppm','20 ppm','80 ppm'],
      correct: 2,
      explanation: 'Recommended NO dose = 20 ppm. Above this increases MetHb/NO2 risk without added benefit.',
    },
    {
      id: 'q-emph-06',
      topic: 'smoking-cessation',
      course: 'rcp104',
      difficulty: 1,
      q: 'Zyban (used for smoking cessation) is the trade name for?',
      choices: ['Varenicline','Bupropion','Clonidine','Nortriptyline'],
      correct: 1,
      explanation: 'Bupropion (Zyban, also Wellbutrin) — antidepressant first-line smoking cessation aid.',
    },
    {
      id: 'q-emph-07',
      topic: 'smoking-cessation',
      course: 'rcp104',
      difficulty: 2,
      q: 'Chantix (varenicline) mechanism of action?',
      choices: ['MAO inhibitor','Selective α4β2 nicotinic acetylcholine receptor partial agonist','β-blocker','SSRI'],
      correct: 1,
      explanation: 'Varenicline (Chantix) is a partial agonist at the α4β2 nicotinic ACh receptor — highest quit rate (~39%).',
    },
    {
      id: 'q-emph-08',
      topic: 'smoking-cessation',
      course: 'rcp104',
      difficulty: 2,
      q: 'First-line nicotine replacement therapy (NRT) formulations include all EXCEPT?',
      choices: ['Transdermal patch','Chewing gum','Lozenge / inhaler','Clonidine'],
      correct: 3,
      explanation: 'Clonidine and nortriptyline are SECOND-line. First-line = NRT (patch, gum, lozenge, inhaler, nasal spray) + bupropion + varenicline.',
    },
    {
      id: 'q-emph-09',
      topic: 'emphysema-rx',
      course: 'rcp104',
      difficulty: 3,
      q: 'α1-Proteinase Inhibitor (API) therapy is given how?',
      choices: ['Aerosolized via SVN','IV infusion, 60 mg/kg once weekly','PO daily','IM monthly'],
      correct: 1,
      explanation: 'API (Prolastin-C, Zemaira, Aralast NP, Glassia) — IV at 60 mg/kg once weekly. Cannot reverse damage; very expensive.',
    },
    {
      id: 'q-emph-10',
      topic: 'nitric-oxide',
      course: 'rcp104',
      difficulty: 3,
      q: 'Inhaled NO is contraindicated in neonates with?',
      choices: ['Pulmonary hypertension','Right-to-left shunt dependence','Bronchopulmonary dysplasia','RDS'],
      correct: 1,
      explanation: 'NO is contraindicated in neonates dependent on a right-to-left shunt (e.g., certain congenital heart defects).',
    },
  ];
  const groupTopics = ['corticosteroids','nonsteroidal','leukotrienes','antiinfective','pentamidine','ribavirin','cf','antimicrobial','tb-meds','vap-meds','cold-cough','mucolytics','emphysema-rx','nitric-oxide','smoking-cessation'];
  const existing = (window.ALL_QUESTIONS || []).filter(q => !(q.course === 'rcp104' && groupTopics.includes(q.topic)));
  window.ALL_QUESTIONS = existing.concat(additions);
})();
