/* ============================================================
   RCP 103 QUESTIONS — Group B (ards, ild, sleep, neuro, pvd)
   ============================================================ */
(function () {
  const additions = [
    // ---------------- ARDS (10) ----------------
    {
      id: 'q-ards-01',
      topic: 'ards',
      course: 'rcp103',
      difficulty: 1,
      q: 'Per the Berlin definition of ARDS, SEVERE ARDS is defined as a P/F ratio of:',
      choices: ['> 300', '200–300', '100–200', '≤ 100'],
      correct: 3,
      explanation: 'Berlin severity (with PEEP ≥ 5): Mild 200–300, Moderate 100–200, Severe ≤ 100.',
    },
    {
      id: 'q-ards-02',
      topic: 'ards',
      course: 'rcp103',
      difficulty: 1,
      q: 'What is the recommended lung-protective tidal volume in ARDS?',
      choices: ['10–12 mL/kg actual body weight', '8–10 mL/kg actual body weight', '4–6 mL/kg ideal/predicted body weight', '2–3 mL/kg ideal body weight'],
      correct: 2,
      explanation: 'ARDSnet protocol uses TV 4–6 mL/kg of IDEAL/PREDICTED body weight (NOT actual weight) to limit volutrauma.',
    },
    {
      id: 'q-ards-03',
      topic: 'ards',
      course: 'rcp103',
      difficulty: 1,
      q: 'Which of the following is NOT one of the four Berlin criteria for ARDS?',
      choices: ['Onset within 1 week of insult', 'Bilateral opacities on imaging', 'PCWP > 18 mmHg', 'P/F ratio impaired with PEEP ≥ 5'],
      correct: 2,
      explanation: 'Berlin requires edema NOT explained by cardiac failure (noncardiogenic). PCWP > 18 indicates CARDIOGENIC edema — opposite of ARDS.',
    },
    {
      id: 'q-ards-04',
      topic: 'ards',
      course: 'rcp103',
      difficulty: 2,
      q: 'A patient has PaO2 80 on FiO2 1.0 with PEEP 8. What is the P/F ratio and ARDS severity?',
      choices: ['80; mild', '80; moderate', '80; severe', '160; moderate'],
      correct: 2,
      explanation: 'P/F = 80/1.0 = 80. P/F ≤ 100 with PEEP ≥ 5 = SEVERE ARDS.',
    },
    {
      id: 'q-ards-05',
      topic: 'ards',
      course: 'rcp103',
      difficulty: 2,
      q: 'Prone positioning in ARDS is indicated for which P/F threshold?',
      choices: ['P/F < 300', 'P/F < 200', 'P/F < 150', 'P/F < 50'],
      correct: 2,
      explanation: 'Prone positioning is recommended for moderate-severe ARDS with P/F < 150 — improves V/Q matching and reduces mortality.',
    },
    {
      id: 'q-ards-06',
      topic: 'ards',
      course: 'rcp103',
      difficulty: 2,
      q: 'What is the target plateau pressure in lung-protective ventilation for ARDS?',
      choices: ['≤ 30 cmH2O', '≤ 40 cmH2O', '≤ 50 cmH2O', '≤ 60 cmH2O'],
      correct: 0,
      explanation: 'ARDSnet targets plateau pressure ≤ 30 cmH2O to limit barotrauma.',
    },
    {
      id: 'q-ards-07',
      topic: 'ards',
      course: 'rcp103',
      difficulty: 2,
      q: 'What is the MOST COMMON cause of ARDS?',
      choices: ['Aspiration', 'Sepsis', 'Pancreatitis', 'TRALI'],
      correct: 1,
      explanation: 'Sepsis is the most common cause of ARDS, followed by pneumonia, aspiration, and trauma.',
    },
    {
      id: 'q-ards-08',
      topic: 'ards',
      course: 'rcp103',
      difficulty: 2,
      q: 'Surfactant in ARDS is primarily affected by:',
      choices: ['Excessive production by Type II cells', 'Dysfunction from inflammatory damage to the alveolar-capillary membrane', 'Genetic deficiency', 'Increased compliance from washout'],
      correct: 1,
      explanation: 'ARDS causes surfactant DYSFUNCTION from inflammatory damage → alveolar collapse, hyaline membranes, and refractory hypoxemia.',
    },
    {
      id: 'q-ards-09',
      topic: 'ards',
      course: 'rcp103',
      difficulty: 3,
      q: 'In ARDS, the ARDSnet protocol allows "permissive hypercapnia" as long as the pH stays above:',
      choices: ['7.10', '7.20', '7.30', '7.35'],
      correct: 1,
      explanation: 'Permissive hypercapnia is allowed (PaCO2 may rise) provided pH remains > 7.20 — trades CO2 control for lung protection.',
    },
    {
      id: 'q-ards-10',
      topic: 'ards',
      course: 'rcp103',
      difficulty: 3,
      q: 'Which neuromuscular blocker is used in severe early ARDS to improve patient-ventilator synchrony?',
      choices: ['Succinylcholine', 'Rocuronium', 'Cisatracurium', 'Vecuronium'],
      correct: 2,
      explanation: 'Cisatracurium is used for severe early ARDS to improve synchrony with the ventilator and reduce barotrauma.',
    },

    // ---------------- ILD (10) ----------------
    {
      id: 'q-ild-01',
      topic: 'ild',
      course: 'rcp103',
      difficulty: 1,
      q: 'The classic PFT pattern of ILD is:',
      choices: ['Obstructive: ↓ FEV1/FVC, ↑ TLC', 'Restrictive: ↓ TLC, normal/↑ FEV1/FVC', 'Mixed obstructive-restrictive', 'Normal PFTs with isolated ↑ DLCO'],
      correct: 1,
      explanation: 'ILD is RESTRICTIVE: ↓ TLC, VC, FVC, FRC, RV with NORMAL or INCREASED FEV1/FVC ratio (> 0.70).',
    },
    {
      id: 'q-ild-02',
      topic: 'ild',
      course: 'rcp103',
      difficulty: 1,
      q: 'DLCO in most ILDs (including IPF) is typically:',
      choices: ['Increased', 'Normal', 'Reduced', 'Variable, unrelated to diffusion'],
      correct: 2,
      explanation: 'Thickened alveolar-capillary membrane → impaired diffusion → REDUCED DLCO in most ILDs.',
    },
    {
      id: 'q-ild-03',
      topic: 'ild',
      course: 'rcp103',
      difficulty: 1,
      q: 'Asbestosis is classically associated with which occupational group?',
      choices: ['Coal miners', 'Sandblasters and stonecutters', 'Shipyard workers, insulators, and pipefitters', 'Cotton textile workers'],
      correct: 2,
      explanation: 'Asbestos exposure: shipyard workers, insulators, pipefitters, brake-lining workers. CXR: pleural plaques, lower-lobe fibrosis.',
    },
    {
      id: 'q-ild-04',
      topic: 'ild',
      course: 'rcp103',
      difficulty: 1,
      q: 'Which two antifibrotic medications are first-line for idiopathic pulmonary fibrosis (IPF)?',
      choices: ['Prednisone and azathioprine', 'Pirfenidone and nintedanib', 'Cyclophosphamide and methotrexate', 'Bosentan and sildenafil'],
      correct: 1,
      explanation: 'Pirfenidone (Esbriet) and nintedanib (OFEV) are first-line antifibrotics for IPF — slow progression but do not reverse fibrosis.',
    },
    {
      id: 'q-ild-05',
      topic: 'ild',
      course: 'rcp103',
      difficulty: 2,
      q: '"Eggshell calcification" of hilar lymph nodes and upper-lobe nodular fibrosis are classic for:',
      choices: ['Asbestosis', 'Silicosis', 'Coal worker\'s pneumoconiosis', 'Berylliosis'],
      correct: 1,
      explanation: 'Silicosis (miners, sandblasters, foundry workers) shows upper-lobe nodular fibrosis and "eggshell calcification" of hilar nodes.',
    },
    {
      id: 'q-ild-06',
      topic: 'ild',
      course: 'rcp103',
      difficulty: 2,
      q: '"Farmer\'s lung" and "bird fancier\'s lung" are types of:',
      choices: ['Byssinosis', 'Coal worker\'s pneumoconiosis', 'Hypersensitivity pneumonitis', 'Berylliosis'],
      correct: 2,
      explanation: 'Hypersensitivity pneumonitis is caused by inhaled organic antigens — moldy hay (farmer\'s lung), avian proteins (bird fancier\'s lung).',
    },
    {
      id: 'q-ild-07',
      topic: 'ild',
      course: 'rcp103',
      difficulty: 2,
      q: 'Byssinosis ("Monday morning fever") is caused by inhalation of:',
      choices: ['Cotton dust', 'Coal dust', 'Beryllium', 'Silica'],
      correct: 0,
      explanation: 'Byssinosis affects cotton/textile workers — symptoms classically peak on Mondays after weekend break ("Monday morning fever").',
    },
    {
      id: 'q-ild-08',
      topic: 'ild',
      course: 'rcp103',
      difficulty: 2,
      q: 'On HRCT, "honeycombing" with traction bronchiectasis is an end-stage finding in:',
      choices: ['Sarcoidosis', 'Idiopathic pulmonary fibrosis (IPF)', 'Hypersensitivity pneumonitis', 'COPD'],
      correct: 1,
      explanation: 'Honeycombing — clusters of cystic airspaces with thick fibrous walls — is the end-stage CT hallmark of IPF.',
    },
    {
      id: 'q-ild-09',
      topic: 'ild',
      course: 'rcp103',
      difficulty: 3,
      q: 'DLCO is FALSELY ELEVATED in which conditions?',
      choices: ['IPF and asbestosis', 'Goodpasture\'s syndrome and idiopathic pulmonary hemosiderosis', 'Sarcoidosis and berylliosis', 'Silicosis and CWP'],
      correct: 1,
      explanation: 'Alveolar hemorrhage (Goodpasture\'s, idiopathic pulmonary hemosiderosis): extravasated RBCs/Hgb bind CO during DLCO test → falsely elevated.',
    },
    {
      id: 'q-ild-10',
      topic: 'ild',
      course: 'rcp103',
      difficulty: 3,
      q: 'Berylliosis is associated with which industries?',
      choices: ['Coal mining', 'Cotton textile', 'Aerospace, electronics, ceramics, dental alloys', 'Shipbuilding and pipefitting'],
      correct: 2,
      explanation: 'Beryllium exposure: aerospace, electronics, ceramics, dental alloys. Produces granulomas similar to sarcoidosis.',
    },

    // ---------------- SLEEP APNEA (10) ----------------
    {
      id: 'q-sleep-01',
      topic: 'sleep-apnea',
      course: 'rcp103',
      difficulty: 1,
      q: 'What is the FIRST-LINE therapy for obstructive sleep apnea (OSA)?',
      choices: ['Modafinil', 'CPAP', 'Acetazolamide', 'Tracheostomy'],
      correct: 1,
      explanation: 'CPAP is the gold-standard first-line therapy for OSA — splints the upper airway open with constant pressure (5–20 cmH2O).',
    },
    {
      id: 'q-sleep-02',
      topic: 'sleep-apnea',
      course: 'rcp103',
      difficulty: 1,
      q: 'The KEY difference between OSA and CSA is:',
      choices: ['OSA has no respiratory effort; CSA has effort', 'OSA has respiratory effort; CSA has NO effort', 'Both have absent effort', 'Both have preserved effort'],
      correct: 1,
      explanation: 'In OSA the airway is physically blocked but respiratory EFFORT persists. In CSA the brain fails to signal — NO respiratory effort.',
    },
    {
      id: 'q-sleep-03',
      topic: 'sleep-apnea',
      course: 'rcp103',
      difficulty: 1,
      q: 'The gold-standard diagnostic test for sleep apnea is:',
      choices: ['Home pulse oximetry overnight', 'Polysomnography (in-lab sleep study)', 'Apnea-hypopnea questionnaire', 'STOP-BANG score alone'],
      correct: 1,
      explanation: 'Polysomnography (PSG, in-lab sleep study) is the GOLD STANDARD. Home sleep apnea testing (HSAT) is acceptable for high-pretest probability.',
    },
    {
      id: 'q-sleep-04',
      topic: 'sleep-apnea',
      course: 'rcp103',
      difficulty: 1,
      q: 'Severe OSA is defined by an apnea-hypopnea index (AHI) of:',
      choices: ['5–15 events/hr', '15–30 events/hr', '> 30 events/hr', '> 50 events/hr'],
      correct: 2,
      explanation: 'AHI severity: Mild 5–15, Moderate 15–30, Severe > 30 events/hr.',
    },
    {
      id: 'q-sleep-05',
      topic: 'sleep-apnea',
      course: 'rcp103',
      difficulty: 2,
      q: 'Cheyne-Stokes breathing — crescendo-decrescendo respirations alternating with central apneas — is classically seen in:',
      choices: ['COPD exacerbation', 'Heart failure', 'Acute asthma', 'Sepsis'],
      correct: 1,
      explanation: 'Cheyne-Stokes is the hallmark central sleep apnea pattern in heart failure (and high altitude).',
    },
    {
      id: 'q-sleep-06',
      topic: 'sleep-apnea',
      course: 'rcp103',
      difficulty: 2,
      q: 'Which medication is approved for RESIDUAL excessive daytime sleepiness in OSA patients who are CPAP-adherent?',
      choices: ['Acetazolamide', 'Modafinil', 'Medroxyprogesterone', 'Zolpidem'],
      correct: 1,
      explanation: 'Modafinil (Provigil) treats residual EDS in patients adherent to CPAP. It does NOT replace CPAP.',
    },
    {
      id: 'q-sleep-07',
      topic: 'sleep-apnea',
      course: 'rcp103',
      difficulty: 2,
      q: 'Which is NOT a typical risk factor for OSA?',
      choices: ['Obesity (BMI > 30)', 'Large neck circumference', 'Female sex without comorbidities', 'Retrognathia'],
      correct: 2,
      explanation: 'OSA risk factors: obesity, large neck circumference (> 17" men, > 16" women), MALE sex, retrognathia, large tongue/tonsils.',
    },
    {
      id: 'q-sleep-08',
      topic: 'sleep-apnea',
      course: 'rcp103',
      difficulty: 2,
      q: 'A "mixed" sleep apnea event is characterized by:',
      choices: ['Effort throughout the entire event', 'No effort throughout the event', 'Starts central (no effort), then becomes obstructive (effort returns, airway closed)', 'Starts obstructive, then resolves'],
      correct: 2,
      explanation: 'Mixed apnea begins as central (no effort) then transitions to obstructive (effort returns but airway remains closed). Treated like OSA.',
    },
    {
      id: 'q-sleep-09',
      topic: 'sleep-apnea',
      course: 'rcp103',
      difficulty: 3,
      q: 'Why does morning headache occur in OSA patients?',
      choices: ['Sleep deprivation alone', 'CO2 retention from nocturnal hypoventilation', 'Dehydration from mouth breathing', 'Caffeine withdrawal'],
      correct: 1,
      explanation: 'Morning headache in OSA reflects nocturnal CO2 retention — hypercapnia causes cerebral vasodilation and headache.',
    },
    {
      id: 'q-sleep-10',
      topic: 'sleep-apnea',
      course: 'rcp103',
      difficulty: 3,
      q: 'Adaptive Servo-Ventilation (ASV) for hyperventilation-related CSA should be AVOIDED in patients with:',
      choices: ['BMI > 35', 'COPD', 'Heart failure with EF < 45%', 'Diabetes'],
      correct: 2,
      explanation: 'ASV is contraindicated in HF with EF < 45% — associated with increased mortality (SERVE-HF trial).',
    },

    // ---------------- NEURO-RESP (10) ----------------
    {
      id: 'q-neuro-01',
      topic: 'neuro-resp',
      course: 'rcp103',
      difficulty: 1,
      q: 'The phrenic nerve, which innervates the diaphragm, originates from which spinal levels?',
      choices: ['C1–C2', 'C3, C4, C5', 'C6, C7, C8', 'T1–T4'],
      correct: 1,
      explanation: 'Mnemonic: "C3, 4, 5 keeps the diaphragm alive." Phrenic nerve arises from anterior rami of C3–C5.',
    },
    {
      id: 'q-neuro-02',
      topic: 'neuro-resp',
      course: 'rcp103',
      difficulty: 1,
      q: 'Guillain-Barré syndrome is characterized by:',
      choices: ['Descending paralysis, preserved reflexes', 'Ascending symmetric paralysis with areflexia', 'Unilateral facial droop', 'Spastic paralysis with hyperreflexia'],
      correct: 1,
      explanation: 'GBS: symmetric ASCENDING weakness beginning in legs, loss of deep tendon reflexes (areflexia), often post-infectious.',
    },
    {
      id: 'q-neuro-03',
      topic: 'neuro-resp',
      course: 'rcp103',
      difficulty: 1,
      q: 'Botulism causes a DESCENDING paralysis classically presenting with the "4 D\'s":',
      choices: ['Dyspnea, dysphonia, dystonia, dyskinesia', 'Diplopia, dysphagia, dysarthria, droopy eyelids', 'Dizziness, diarrhea, dysuria, dehydration', 'Dementia, depression, delirium, drowsiness'],
      correct: 1,
      explanation: 'Botulism 4 D\'s: Diplopia, Dysphagia, Dysarthria, Droopy eyelids (ptosis). Toxin blocks ACh release at NMJ.',
    },
    {
      id: 'q-neuro-04',
      topic: 'neuro-resp',
      course: 'rcp103',
      difficulty: 1,
      q: 'A maximum inspiratory pressure (MIP/NIF) more negative than which value suggests adequate strength for extubation?',
      choices: ['−10 cmH2O', '−15 cmH2O', '−20 cmH2O', '−30 cmH2O'],
      correct: 3,
      explanation: 'MIP more negative than −30 cmH2O = adequate inspiratory strength. MIP less negative than −20 to −25 = cannot wean.',
    },
    {
      id: 'q-neuro-05',
      topic: 'neuro-resp',
      course: 'rcp103',
      difficulty: 2,
      q: 'The Guillain-Barré "20-30-40 rule" for considering intubation is:',
      choices: ['VC < 20 mL/kg, MIP weaker than −30, MEP < 40', 'RR > 20, HR > 30, SpO2 < 40', 'PaO2 < 20, PaCO2 > 30, pH < 7.40', 'Age > 20, MIP > 30, MEP > 40'],
      correct: 0,
      explanation: '20-30-40 rule: VC < 20 mL/kg, MIP weaker than −30, MEP < 40 → intubate BEFORE patient crashes.',
    },
    {
      id: 'q-neuro-06',
      topic: 'neuro-resp',
      course: 'rcp103',
      difficulty: 2,
      q: 'A spinal cord injury ABOVE C3 typically results in:',
      choices: ['Mild reduction in FVC only', 'Permanent ventilator dependence', 'Intact diaphragm with weak intercostals', 'No respiratory effect'],
      correct: 1,
      explanation: 'Injuries above C3 lose diaphragm and accessory muscle function → permanent ventilator dependence (phrenic pacers may help).',
    },
    {
      id: 'q-neuro-07',
      topic: 'neuro-resp',
      course: 'rcp103',
      difficulty: 2,
      q: 'CSF analysis in Guillain-Barré classically shows:',
      choices: ['Elevated WBCs with normal protein', 'Elevated protein with normal WBCs (albuminocytological dissociation)', 'Low glucose and elevated lactate', 'Bloody tap with xanthochromia'],
      correct: 1,
      explanation: 'GBS shows "albuminocytological dissociation" — elevated CSF protein with normal WBC count.',
    },
    {
      id: 'q-neuro-08',
      topic: 'neuro-resp',
      course: 'rcp103',
      difficulty: 2,
      q: 'First-line treatment for Guillain-Barré syndrome is:',
      choices: ['High-dose corticosteroids', 'IVIG or plasmapheresis', 'Pyridostigmine', 'Botulism antitoxin'],
      correct: 1,
      explanation: 'GBS is treated with IVIG or plasmapheresis. Steroids do NOT work in GBS. Pyridostigmine is for myasthenia gravis.',
    },
    {
      id: 'q-neuro-09',
      topic: 'neuro-resp',
      course: 'rcp103',
      difficulty: 3,
      q: 'Which of the following BEST distinguishes botulism from Guillain-Barré early in presentation?',
      choices: ['Areflexia in botulism', 'Pupillary involvement (dilated, unresponsive) in botulism', 'Ascending weakness in botulism', 'Elevated CSF protein in botulism'],
      correct: 1,
      explanation: 'Botulism causes dilated, unresponsive pupils and preserved DTRs early. GBS spares pupils and produces areflexia.',
    },
    {
      id: 'q-neuro-10',
      topic: 'neuro-resp',
      course: 'rcp103',
      difficulty: 3,
      q: 'The PRIMARY respiratory therapy concern in a stroke patient with bulbar dysphagia is:',
      choices: ['Bronchospasm', 'Aspiration and aspiration pneumonia', 'Pulmonary embolism', 'Air trapping'],
      correct: 1,
      explanation: 'Dysphagia in stroke → aspiration risk → aspiration pneumonia, hypoxemia, ARDS. NPO until bedside swallow evaluation cleared.',
    },

    // ---------------- PULMONARY EDEMA / PVD (10) ----------------
    {
      id: 'q-pe-01',
      topic: 'pulm-edema',
      course: 'rcp103',
      difficulty: 1,
      q: 'A PCWP > 18 mmHg is the hallmark of which type of pulmonary edema?',
      choices: ['Cardiogenic', 'Noncardiogenic (ARDS)', 'High-altitude (HAPE)', 'Neurogenic'],
      correct: 0,
      explanation: 'PCWP > 18 mmHg = elevated left atrial/LV filling pressure = CARDIOGENIC edema. Noncardiogenic (ARDS) has NORMAL PCWP.',
    },
    {
      id: 'q-pe-02',
      topic: 'pulm-edema',
      course: 'rcp103',
      difficulty: 1,
      q: 'The "LMNOP" treatment mnemonic for cardiogenic pulmonary edema includes:',
      choices: ['Lasix, Morphine, Nitroglycerin, Oxygen, Positioning/positive pressure', 'Levalbuterol, Magnesium, Naloxone, Oxygen, Prednisone', 'Lactulose, Metoprolol, Norepinephrine, Oxygen, Propranolol', 'Lasix, Mannitol, Nitric oxide, Oseltamivir, Phenylephrine'],
      correct: 0,
      explanation: 'LMNOP: Lasix (diuresis), Morphine (preload reduction), Nitroglycerin (preload/afterload), Oxygen, Positioning upright + CPAP/BiPAP.',
    },
    {
      id: 'q-pe-03',
      topic: 'pulm-edema',
      course: 'rcp103',
      difficulty: 1,
      q: 'The gold-standard imaging test for pulmonary embolism is:',
      choices: ['Chest X-ray', 'V/Q scan', 'CT pulmonary angiogram (CT-PA)', 'Transthoracic echocardiogram'],
      correct: 2,
      explanation: 'CT-PA is the gold standard for diagnosing PE. V/Q scan is used when contrast is contraindicated.',
    },
    {
      id: 'q-pe-04',
      topic: 'pulm-edema',
      course: 'rcp103',
      difficulty: 1,
      q: 'Virchow\'s triad describes risk factors for thromboembolism. Which is NOT a component?',
      choices: ['Venous stasis', 'Endothelial injury', 'Hypercoagulability', 'Hypoxic vasoconstriction'],
      correct: 3,
      explanation: 'Virchow\'s triad: venous stasis, endothelial injury, hypercoagulability. Hypoxic vasoconstriction is a separate mechanism.',
    },
    {
      id: 'q-pe-05',
      topic: 'pulm-edema',
      course: 'rcp103',
      difficulty: 2,
      q: 'The V/Q effect of a pulmonary embolism is BEST described as:',
      choices: ['Shunt (low V/Q)', 'Dead space (high V/Q — ventilation without perfusion)', 'Diffusion defect only', 'Normal V/Q matching'],
      correct: 1,
      explanation: 'PE blocks PERFUSION but ventilation continues → high V/Q ratio = DEAD SPACE physiology in the affected segment.',
    },
    {
      id: 'q-pe-06',
      topic: 'pulm-edema',
      course: 'rcp103',
      difficulty: 2,
      q: 'The classic but rarely seen ECG finding in pulmonary embolism is:',
      choices: ['ST-elevation in V1–V4', 'S1Q3T3 pattern', 'Diffuse PR depression', 'Delta wave'],
      correct: 1,
      explanation: 'S1Q3T3 (S in lead I, Q and inverted T in lead III) is classic for PE but uncommon. Sinus tachycardia is the most common ECG finding.',
    },
    {
      id: 'q-pe-07',
      topic: 'pulm-edema',
      course: 'rcp103',
      difficulty: 2,
      q: 'A CXR showing cardiomegaly, Kerley B lines, and a perihilar "bat-wing" pattern suggests:',
      choices: ['ARDS / noncardiogenic edema', 'Cardiogenic pulmonary edema', 'Lobar pneumonia', 'Pulmonary embolism'],
      correct: 1,
      explanation: 'Cardiomegaly + Kerley B lines + bat-wing/butterfly perihilar pattern + pleural effusions = cardiogenic edema.',
    },
    {
      id: 'q-pe-08',
      topic: 'pulm-edema',
      course: 'rcp103',
      difficulty: 2,
      q: 'Cor pulmonale is defined as:',
      choices: ['Left ventricular failure from primary lung disease', 'Right ventricular hypertrophy and failure from primary lung disease causing pulmonary hypertension', 'Biventricular failure from MI', 'Atrial fibrillation due to chronic hypoxia'],
      correct: 1,
      explanation: 'Cor pulmonale = RV hypertrophy/failure caused by primary lung disease producing pulmonary hypertension. COPD is the most common cause.',
    },
    {
      id: 'q-pe-09',
      topic: 'pulm-edema',
      course: 'rcp103',
      difficulty: 3,
      q: 'Per the 2018 World Symposium, pulmonary hypertension is now defined as mean PAP at rest greater than:',
      choices: ['15 mmHg', '20 mmHg', '25 mmHg', '30 mmHg'],
      correct: 1,
      explanation: 'Pulmonary HTN is now defined as mPAP > 20 mmHg at rest (formerly > 25 mmHg before the 2018 update).',
    },
    {
      id: 'q-pe-10',
      topic: 'pulm-edema',
      course: 'rcp103',
      difficulty: 3,
      q: 'In the WHO classification, COPD, ILD, and OSA cause pulmonary hypertension via which group?',
      choices: ['Group 1 (PAH)', 'Group 2 (left heart disease)', 'Group 3 (lung disease/hypoxia)', 'Group 4 (CTEPH)'],
      correct: 2,
      explanation: 'Group 3 PH is due to lung disease/hypoxia — COPD, ILD, OSA. "COPD goes here."',
    },
  ];
  const groupTopics = ['ards','ild','sleep-apnea','neuro-resp','pulm-edema'];
  const existing = (window.ALL_QUESTIONS || []).filter(q => !(q.course === 'rcp103' && groupTopics.includes(q.topic)));
  window.ALL_QUESTIONS = existing.concat(additions);
})();
