/* ============================================================
   RCP 104 QUESTIONS — Group B (Chapters 18–23)
   ============================================================ */
(function () {
  const additions = [
    /* ---------- Ch 18 · Neuromuscular Blocking Agents (10) ---------- */
    {
      id: 'q-nmba-01',
      topic: 'nmba',
      course: 'rcp104',
      difficulty: 1,
      q: 'Neuromuscular blocking agents (NMBAs) produce what primary effect?',
      choices: ['CNS sedation','Skeletal muscle paralysis','Bronchodilation','Analgesia'],
      correct: 1,
      explanation: 'NMBAs paralyze skeletal muscle (including the diaphragm). They provide NO sedation or analgesia — pair with sedative and analgesic.',
    },
    {
      id: 'q-nmba-02',
      topic: 'nmba',
      course: 'rcp104',
      difficulty: 1,
      q: 'Succinylcholine is what type of neuromuscular blocker?',
      choices: ['Non-depolarizing','Depolarizing','Anticholinesterase','Ganglionic blocker'],
      correct: 1,
      explanation: 'Succinylcholine is the ONLY clinically used depolarizing NMBA — produces fasciculations then flaccid paralysis.',
    },
    {
      id: 'q-nmba-03',
      topic: 'nmba',
      course: 'rcp104',
      difficulty: 1,
      q: 'Succinylcholine is contraindicated in which condition?',
      choices: ['Mild hypertension','Recent burns / crush injury / hyperkalemia','Tachycardia','Insomnia'],
      correct: 1,
      explanation: 'Succinylcholine causes K+ release; contraindicated in burns, crush injury, denervation, and hyperkalemia (risk of life-threatening hyperK and cardiac arrest).',
    },
    {
      id: 'q-nmba-04',
      topic: 'nmba',
      course: 'rcp104',
      difficulty: 2,
      q: 'Succinylcholine is most often used for what indication?',
      choices: ['Long-term vent paralysis','Rapid Sequence Intubation (RSI)','Reversal of opioid overdose','Treatment of malignant hyperthermia'],
      correct: 1,
      explanation: 'Succinylcholine has rapid onset (~60–90 sec) and short duration (~10–15 min) — ideal for RSI.',
    },
    {
      id: 'q-nmba-05',
      topic: 'nmba',
      course: 'rcp104',
      difficulty: 2,
      q: 'Which agent is a non-depolarizing NMBA commonly used for sustained paralysis on the ventilator?',
      choices: ['Succinylcholine','Rocuronium','Naloxone','Neostigmine'],
      correct: 1,
      explanation: 'Rocuronium, vecuronium, and cisatracurium are non-depolarizing NMBAs used for continued paralysis. Succinylcholine is depolarizing/short-acting.',
    },
    {
      id: 'q-nmba-06',
      topic: 'nmba',
      course: 'rcp104',
      difficulty: 2,
      q: 'What monitoring is used at the bedside to assess depth of neuromuscular blockade?',
      choices: ['EtCO2','Train-of-four (TOF)','Pulse oximetry','BIS monitor'],
      correct: 1,
      explanation: 'Train-of-four (TOF) — 4 stimuli over the ulnar nerve; goal in ICU is typically 1–2 twitches out of 4.',
    },
    {
      id: 'q-nmba-07',
      topic: 'nmba',
      course: 'rcp104',
      difficulty: 2,
      q: 'Sugammadex is used to reverse which neuromuscular blocker?',
      choices: ['Succinylcholine','Rocuronium / vecuronium','Cisatracurium','Pancuronium only'],
      correct: 1,
      explanation: 'Sugammadex encapsulates rocuronium (and vecuronium) — rapid, complete reversal. NOT used for succinylcholine.',
    },
    {
      id: 'q-nmba-08',
      topic: 'nmba',
      course: 'rcp104',
      difficulty: 2,
      q: 'Neostigmine is paired with glycopyrrolate during NMBA reversal because:',
      choices: ['Glycopyrrolate boosts paralysis','Glycopyrrolate blocks muscarinic side effects (bradycardia, secretions)','Glycopyrrolate is a sedative','Glycopyrrolate is the actual reversal agent'],
      correct: 1,
      explanation: 'Neostigmine (anticholinesterase) reverses non-depolarizing block but causes bradycardia/secretions; glycopyrrolate (antimuscarinic) blocks those effects.',
    },
    {
      id: 'q-nmba-09',
      topic: 'nmba',
      course: 'rcp104',
      difficulty: 3,
      q: 'A patient on succinylcholine develops rigidity, hyperthermia, and rising EtCO2. What is the most likely diagnosis?',
      choices: ['Anaphylaxis','Malignant hyperthermia','Serotonin syndrome','Hypoglycemia'],
      correct: 1,
      explanation: 'Succinylcholine (and volatile anesthetics) can trigger malignant hyperthermia. Treatment = dantrolene.',
    },
    {
      id: 'q-nmba-10',
      topic: 'nmba',
      course: 'rcp104',
      difficulty: 3,
      q: 'A paralyzed, ventilated patient receiving NMBA infusion is awake. What is the MOST important consideration?',
      choices: ['Increase NMBA dose','Always provide sedation AND analgesia — NMBAs do not sedate','Stop the ventilator','Switch to succinylcholine'],
      correct: 1,
      explanation: 'NMBAs paralyze but do NOT sedate or relieve pain. Patient awareness while paralyzed is catastrophic — always co-administer sedation and analgesia.',
    },

    /* ---------- Ch 19 · Diuretics (10) ---------- */
    {
      id: 'q-diur-01',
      topic: 'diuretics',
      course: 'rcp104',
      difficulty: 1,
      q: 'Which class of diuretic is the MOST POTENT?',
      choices: ['Thiazide','Loop','Potassium-sparing','Carbonic anhydrase inhibitor'],
      correct: 1,
      explanation: 'Loop diuretics (e.g., furosemide) are the most potent — they block Na/K/2Cl reabsorption in the thick ascending limb.',
    },
    {
      id: 'q-diur-02',
      topic: 'diuretics',
      course: 'rcp104',
      difficulty: 1,
      q: "Furosemide's trade name is?",
      choices: ['Lasix','Bumex','Aldactone','Diamox'],
      correct: 0,
      explanation: 'Furosemide = Lasix. Most common loop diuretic; IV used for acute pulmonary edema/CHF.',
    },
    {
      id: 'q-diur-03',
      topic: 'diuretics',
      course: 'rcp104',
      difficulty: 1,
      q: 'Approximately what percentage of cardiac output flows through the renal system?',
      choices: ['5%','10%','~22%','50%'],
      correct: 2,
      explanation: 'About 22% of cardiac output (~1.1 L/min) perfuses the kidneys (Ch 19).',
    },
    {
      id: 'q-diur-04',
      topic: 'diuretics',
      course: 'rcp104',
      difficulty: 1,
      q: 'Which diuretic is used to reduce cerebral edema and elevated ICP?',
      choices: ['Furosemide','Mannitol (osmotic)','Spironolactone','Hydrochlorothiazide'],
      correct: 1,
      explanation: 'Mannitol is an osmotic diuretic that draws fluid out of the brain — reduces cerebral edema/ICP.',
    },
    {
      id: 'q-diur-05',
      topic: 'diuretics',
      course: 'rcp104',
      difficulty: 2,
      q: "Spironolactone (Aldactone) is what type of diuretic?",
      choices: ['Loop','Thiazide','Potassium-sparing (aldosterone antagonist)','Osmotic'],
      correct: 2,
      explanation: 'Spironolactone is a K-sparing aldosterone antagonist; side effect = gynecomastia.',
    },
    {
      id: 'q-diur-06',
      topic: 'diuretics',
      course: 'rcp104',
      difficulty: 2,
      q: 'A patient on long-term Lasix is at greatest risk for which electrolyte abnormality?',
      choices: ['Hyperkalemia','Hypokalemia','Hypernatremia','Hyperphosphatemia'],
      correct: 1,
      explanation: 'Loop diuretics waste K+ — hypokalemia is the classic adverse effect (also hypomagnesemia, hypocalcemia).',
    },
    {
      id: 'q-diur-07',
      topic: 'diuretics',
      course: 'rcp104',
      difficulty: 2,
      q: 'Which side effect is most uniquely associated with high-dose IV furosemide?',
      choices: ['Pulmonary fibrosis','Ototoxicity (tinnitus / hearing loss)','Cataracts','Hepatic failure'],
      correct: 1,
      explanation: 'Rapid IV push of furosemide can cause ototoxicity (especially with aminoglycosides). Give slowly.',
    },
    {
      id: 'q-diur-08',
      topic: 'diuretics',
      course: 'rcp104',
      difficulty: 2,
      q: 'Thiazide diuretics can worsen which metabolic condition?',
      choices: ['Hypoglycemia','Hyperglycemia (and hyperuricemia)','Hypothyroidism','Hypocalcemia'],
      correct: 1,
      explanation: 'Thiazides cause hyperglycemia, hyperuricemia (gout), hypokalemia, and hypercalcemia.',
    },
    {
      id: 'q-diur-09',
      topic: 'diuretics',
      course: 'rcp104',
      difficulty: 3,
      q: 'Combining a loop diuretic with a thiazide for refractory edema is an example of what?',
      choices: ['Antagonistic effect','Synergistic effect','Additive only','Idiosyncratic reaction'],
      correct: 1,
      explanation: 'Loop + thiazide (e.g., metolazone) produces synergistic diuresis — far greater than either alone.',
    },
    {
      id: 'q-diur-10',
      topic: 'diuretics',
      course: 'rcp104',
      difficulty: 3,
      q: 'Which electrolyte panel is NOT in the standard "common electrolytes" set (Box 19.1)?',
      choices: ['Sodium (Na)','Potassium (K)','Iron (Fe)','Calcium (Ca)'],
      correct: 2,
      explanation: 'Common electrolytes: Na, K, Cl, HCO3, Ca, Mg, PO4. Iron is a trace mineral, not a routine electrolyte.',
    },

    /* ---------- Ch 20 · CNS Drugs (10) ---------- */
    {
      id: 'q-cns-01',
      topic: 'cns-drugs',
      course: 'rcp104',
      difficulty: 1,
      q: 'Which classes of drugs depress the respiratory center?',
      choices: ['Beta-agonists','Opioids, benzodiazepines, and barbiturates','Anticholinergics','ICS'],
      correct: 1,
      explanation: 'Opioids, benzos, barbiturates, and alcohol all depress the medullary respiratory centers.',
    },
    {
      id: 'q-op-02',
      topic: 'opioids',
      course: 'rcp104',
      difficulty: 1,
      q: 'Naloxone (Narcan) is used to reverse?',
      choices: ['Benzodiazepine overdose','Opioid overdose','Alcohol withdrawal','Cocaine toxicity'],
      correct: 1,
      explanation: 'Naloxone is a pure opioid antagonist — reverses respiratory depression and sedation from opioids.',
    },
    {
      id: 'q-bz-03',
      topic: 'benzos',
      course: 'rcp104',
      difficulty: 1,
      q: "Versed's generic name is?",
      choices: ['Lorazepam','Midazolam','Diazepam','Alprazolam'],
      correct: 1,
      explanation: 'Versed = midazolam. Short-acting benzo commonly used for procedural sedation.',
    },
    {
      id: 'q-bz-04',
      topic: 'benzos',
      course: 'rcp104',
      difficulty: 1,
      q: "Ativan's generic name is?",
      choices: ['Lorazepam','Midazolam','Diazepam','Clonazepam'],
      correct: 0,
      explanation: 'Ativan = lorazepam. Used for anxiety, seizures, alcohol withdrawal.',
    },
    {
      id: 'q-op-05',
      topic: 'opioids',
      course: 'rcp104',
      difficulty: 2,
      q: 'A patient using PCA (Patient-Controlled Analgesia) is found unresponsive with RR of 6. First action?',
      choices: ['Increase the PCA dose','Stop PCA, support ventilation, prepare naloxone','Give morphine','Give flumazenil'],
      correct: 1,
      explanation: 'PCA overdose → opioid-induced respiratory depression. Stop the pump, ventilate, and give naloxone.',
    },
    {
      id: 'q-cns-06',
      topic: 'cns-drugs',
      course: 'rcp104',
      difficulty: 2,
      q: 'Which CNS structure houses the medullary respiratory centers?',
      choices: ['Cerebral cortex','Medulla oblongata (brainstem)','Hypothalamus','Cerebellum'],
      correct: 1,
      explanation: 'The medulla contains the inspiratory/expiratory centers. Pons modulates them; hypothalamus regulates homeostasis.',
    },
    {
      id: 'q-cns-07',
      topic: 'cns-drugs',
      course: 'rcp104',
      difficulty: 2,
      q: 'Which is the MOST DANGEROUS complication of severe alcohol withdrawal?',
      choices: ['Headache','Delirium tremens (DTs) and seizures','Constipation','Hypertension only'],
      correct: 1,
      explanation: 'DTs (24–72 h) with seizures, autonomic instability — can be fatal. Treat with benzodiazepines.',
    },
    {
      id: 'q-cns-08',
      topic: 'cns-drugs',
      course: 'rcp104',
      difficulty: 2,
      q: 'NSAIDs (e.g., ibuprofen) are most associated with which adverse effects?',
      choices: ['Respiratory depression','GI bleeding and renal injury','Tardive dyskinesia','Hyperkalemia from K-sparing effect'],
      correct: 1,
      explanation: 'NSAIDs inhibit COX → GI ulcers/bleeding, AKI, HTN, platelet inhibition. NOT respiratory depressants.',
    },
    {
      id: 'q-cns-09',
      topic: 'cns-drugs',
      course: 'rcp104',
      difficulty: 3,
      q: 'Which describes the difference between antidepressants and antipsychotics?',
      choices: ['Same drug class','Antidepressants treat mood (SSRI/SNRI/TCA); antipsychotics treat psychosis/schizophrenia (haloperidol, olanzapine)','Antipsychotics treat depression only','Antidepressants reverse opioids'],
      correct: 1,
      explanation: 'Antidepressants (SSRI/SNRI/TCA/MAOI) treat depression. Antipsychotics (typical/atypical) treat schizophrenia, mania, psychosis.',
    },
    {
      id: 'q-bz-10',
      topic: 'benzos',
      course: 'rcp104',
      difficulty: 3,
      q: 'Which agent reverses benzodiazepine overdose?',
      choices: ['Naloxone','Flumazenil','Neostigmine','Sugammadex'],
      correct: 1,
      explanation: 'Flumazenil is the benzodiazepine antagonist. Use with caution — can precipitate seizures in chronic users.',
    },

    /* ---------- Ch 21 · Vasopressors / Antiarrhythmics (10) ---------- */
    {
      id: 'q-vp-01',
      topic: 'vasopressors',
      course: 'rcp104',
      difficulty: 1,
      q: 'Cardiac output (CO) is calculated as?',
      choices: ['HR × SV','BP × HR','SV ÷ HR','MAP × CVP'],
      correct: 0,
      explanation: 'CO = Heart Rate × Stroke Volume (normal ≈ 4–8 L/min).',
    },
    {
      id: 'q-navel-02',
      topic: 'navel',
      course: 'rcp104',
      difficulty: 1,
      q: 'The NAVEL acronym refers to drugs that can be given via what route?',
      choices: ['Intramuscular','Endotracheal tube (ETT)','Subcutaneous','Oral'],
      correct: 1,
      explanation: 'NAVEL = Naloxone, Atropine, Vasopressin, Epinephrine, Lidocaine — given via ETT when no IV access in code.',
    },
    {
      id: 'q-navel-03',
      topic: 'navel',
      course: 'rcp104',
      difficulty: 1,
      q: 'What does the "N" in NAVEL stand for?',
      choices: ['Nitroglycerin','Naloxone','Norepinephrine','Neostigmine'],
      correct: 1,
      explanation: 'N = Naloxone. NAVEL = Naloxone, Atropine, Vasopressin, Epinephrine, Lidocaine.',
    },
    {
      id: 'q-vp-04',
      topic: 'vasopressors',
      course: 'rcp104',
      difficulty: 1,
      q: 'A respiratory patient with asthma/COPD has which class of cardiac drug as a relative concern?',
      choices: ['ACE inhibitors','Non-selective beta-blockers (worsen bronchospasm)','Statins','Aspirin'],
      correct: 1,
      explanation: 'Non-selective β-blockers (propranolol) block β2 → bronchospasm. Cardioselective (metoprolol) safer.',
    },
    {
      id: 'q-antiarr-05',
      topic: 'antiarrhythmics',
      course: 'rcp104',
      difficulty: 2,
      q: 'Adenosine is the drug of choice for what rhythm?',
      choices: ['VFib','Stable SVT (paroxysmal supraventricular tachycardia)','Asystole','Bradycardia'],
      correct: 1,
      explanation: 'Adenosine 6 mg IV rapid push → 12 mg → converts SVT by transient AV block.',
    },
    {
      id: 'q-vp-06',
      topic: 'vasopressors',
      course: 'rcp104',
      difficulty: 2,
      q: 'Atropine is given primarily to treat?',
      choices: ['VFib','Symptomatic bradycardia','Hypertensive crisis','SVT'],
      correct: 1,
      explanation: 'Atropine 0.5–1 mg IV blocks vagal tone → increases HR. Used for symptomatic bradycardia and organophosphate poisoning.',
    },
    {
      id: 'q-vp-07',
      topic: 'vasopressors',
      course: 'rcp104',
      difficulty: 2,
      q: 'First-line drug in cardiac arrest (VF/VT/asystole/PEA) is?',
      choices: ['Amiodarone','Epinephrine 1 mg IV q3–5 min','Dopamine','Atropine'],
      correct: 1,
      explanation: 'Epinephrine 1 mg IV/IO every 3–5 minutes is the first vasopressor in ACLS cardiac arrest.',
    },
    {
      id: 'q-vp-08',
      topic: 'vasopressors',
      course: 'rcp104',
      difficulty: 3,
      q: 'Which cardiac structure is the normal primary pacemaker?',
      choices: ['AV node','SA (sinoatrial) node','Purkinje fibers','Bundle of His'],
      correct: 1,
      explanation: 'SA node (60–100 bpm) is the primary pacemaker. AV node (40–60) and Purkinje (20–40) are backups.',
    },
    {
      id: 'q-vp-09',
      topic: 'vasopressors',
      course: 'rcp104',
      difficulty: 3,
      q: 'An ICD (Implantable Cardioverter Defibrillator) is most indicated for which patient?',
      choices: ['Stable A-fib','Survivors of sudden cardiac arrest / VT with low EF','First-time syncope','Sinus tachycardia'],
      correct: 1,
      explanation: 'ICDs are indicated for prior VF/VT arrest, EF ≤35%, or high-risk inherited arrhythmia syndromes.',
    },
    {
      id: 'q-antiarr-10',
      topic: 'antiarrhythmics',
      course: 'rcp104',
      difficulty: 3,
      q: 'A patient in pulseless VT is shocked twice without response. Next medication per ACLS?',
      choices: ['Adenosine','Epinephrine, then amiodarone (or lidocaine)','Atropine','Verapamil'],
      correct: 1,
      explanation: 'Shockable rhythm (VF/pVT): CPR + shock → epinephrine 1 mg → amiodarone 300 mg (or lidocaine).',
    },

    /* ---------- Ch 22 · Antihypertensives / MI Rx (10) ---------- */
    {
      id: 'q-htn-01',
      topic: 'antihypertensives',
      course: 'rcp104',
      difficulty: 1,
      q: 'According to current guidelines, hypertension is generally diagnosed at?',
      choices: ['≥120/70','≥130/80','≥140/100','≥160/110'],
      correct: 1,
      explanation: 'ACC/AHA defines Stage 1 HTN as ≥130/80 mmHg.',
    },
    {
      id: 'q-htn-02',
      topic: 'antihypertensives',
      course: 'rcp104',
      difficulty: 1,
      q: "Lisinopril's drug class is?",
      choices: ['ARB','ACE inhibitor','Beta-blocker','Calcium channel blocker'],
      correct: 1,
      explanation: 'Lisinopril (and enalapril, captopril) are ACE inhibitors — block conversion of angiotensin I to II.',
    },
    {
      id: 'q-htn-03',
      topic: 'antihypertensives',
      course: 'rcp104',
      difficulty: 1,
      q: 'The most characteristic side effect of ACE inhibitors is?',
      choices: ['Ankle edema','Dry persistent cough','Hirsutism','Hyperglycemia'],
      correct: 1,
      explanation: 'ACEIs increase bradykinin → dry cough (~10%). Angioedema is the dangerous (rare) effect. Switch to ARB.',
    },
    {
      id: 'q-htn-04',
      topic: 'htn',
      course: 'rcp104',
      difficulty: 2,
      q: 'Which is considered a FIRST-LINE class for treating essential hypertension?',
      choices: ['Alpha-blockers','Thiazide diuretics, ACEI, ARB, or CCB','Beta-blockers only','Loop diuretics'],
      correct: 1,
      explanation: 'First-line agents: thiazide, ACEI, ARB, CCB. Beta- and alpha-blockers are typically second-line in uncomplicated HTN.',
    },
    {
      id: 'q-htn-05',
      topic: 'htn',
      course: 'rcp104',
      difficulty: 2,
      q: 'ACE inhibitors block what enzymatic step?',
      choices: ['Renin release','Conversion of angiotensin I to angiotensin II','Aldosterone receptor','Beta-1 receptor'],
      correct: 1,
      explanation: 'ACEIs block angiotensin-converting enzyme → ↓ AT-II → vasodilation and ↓ aldosterone.',
    },
    {
      id: 'q-mi-06',
      topic: 'mi-rx',
      course: 'rcp104',
      difficulty: 1,
      q: 'Nitroglycerin\'s primary hemodynamic effect is?',
      choices: ['Arterial vasoconstriction','Venodilation → ↓ preload','Positive inotropy','Increased afterload'],
      correct: 1,
      explanation: 'NTG is primarily a venodilator — reduces preload and myocardial O2 demand. Routes: SL, transdermal, IV.',
    },
    {
      id: 'q-mi-07',
      topic: 'mi-rx',
      course: 'rcp104',
      difficulty: 2,
      q: 'What is the difference between ischemia and infarction?',
      choices: ['Same thing','Ischemia = reversible ↓ perfusion; infarction = irreversible tissue death','Ischemia is permanent','Infarction is bleeding'],
      correct: 1,
      explanation: 'Ischemia is reversible reduced blood flow; infarction is necrosis from sustained ischemia.',
    },
    {
      id: 'q-mi-08',
      topic: 'mi-rx',
      course: 'rcp104',
      difficulty: 2,
      q: 'Standard post-MI prophylactic regimen typically includes?',
      choices: ['Aspirin, statin, beta-blocker, ACEI','Furosemide and digoxin','Antihistamine and steroid','Antibiotic and antiviral'],
      correct: 0,
      explanation: 'Post-MI: ASA (antiplatelet), statin, β-blocker (↓O2 demand), ACEI (remodeling). +/− P2Y12 inhibitor.',
    },
    {
      id: 'q-mi-09',
      topic: 'mi-rx',
      course: 'rcp104',
      difficulty: 3,
      q: 'Thrombolytics (e.g., alteplase, streptokinase) carry which major risk?',
      choices: ['Hyperkalemia','Bleeding / intracranial hemorrhage','Bronchospasm','Hyperthermia'],
      correct: 1,
      explanation: 'Fibrinolytics dissolve clots — major risk is bleeding, especially intracranial hemorrhage.',
    },
    {
      id: 'q-mi-10',
      topic: 'mi-rx',
      course: 'rcp104',
      difficulty: 3,
      q: 'Cardiac muscle contraction is critically dependent on which ion?',
      choices: ['Sodium (Na+)','Calcium (Ca++)','Magnesium (Mg++)','Phosphate (PO4)'],
      correct: 1,
      explanation: 'Ca++ influx triggers actin-myosin coupling. Calcium channel blockers reduce contractility by blocking this.',
    },

    /* ---------- Ch 23 · Sleep Pharmacology (10) ---------- */
    {
      id: 'q-sleep-01',
      topic: 'sleep-pharm',
      course: 'rcp104',
      difficulty: 1,
      q: 'The most common sleep disorder is?',
      choices: ['Narcolepsy','Obstructive sleep apnea (OSA)','Restless legs syndrome','Sleepwalking'],
      correct: 1,
      explanation: 'OSA is by far the most common — affects ~25% of adult men, 10% of women.',
    },
    {
      id: 'q-sleep-02',
      topic: 'sleep-pharm',
      course: 'rcp104',
      difficulty: 1,
      q: 'Which hormone signals nighttime / promotes sleep onset?',
      choices: ['Cortisol','Melatonin','Insulin','Adrenaline'],
      correct: 1,
      explanation: 'Melatonin is released by the pineal gland in darkness — signals night to the SCN.',
    },
    {
      id: 'q-sleep-03',
      topic: 'sleep-pharm',
      course: 'rcp104',
      difficulty: 1,
      q: 'The circadian rhythm is governed by which brain region (in response to light)?',
      choices: ['Amygdala','Suprachiasmatic nucleus (SCN) of the hypothalamus','Cerebellum','Pons'],
      correct: 1,
      explanation: 'The SCN in the hypothalamus is the master circadian pacemaker, entrained by light via the retina.',
    },
    {
      id: 'q-sleep-04',
      topic: 'sleep-pharm',
      course: 'rcp104',
      difficulty: 1,
      q: 'Restless Legs Syndrome (RLS) is most associated with dysfunction of which neurotransmitter?',
      choices: ['Serotonin','Dopamine','GABA','Acetylcholine'],
      correct: 1,
      explanation: 'RLS is linked to dopamine dysfunction (often with iron deficiency). Treat with dopamine agonists (pramipexole, ropinirole).',
    },
    {
      id: 'q-sleep-05',
      topic: 'sleep-pharm',
      course: 'rcp104',
      difficulty: 2,
      q: 'During which sleep stage do most vivid dreams and skeletal muscle atonia occur?',
      choices: ['N1 (light)','N2','N3 (deep / slow-wave)','REM'],
      correct: 3,
      explanation: 'REM sleep features rapid eye movement, vivid dreaming, and skeletal-muscle paralysis (except diaphragm/eyes).',
    },
    {
      id: 'q-sleep-06',
      topic: 'sleep-pharm',
      course: 'rcp104',
      difficulty: 2,
      q: 'Which of these is characteristic of narcolepsy?',
      choices: ['Inability to fall asleep at night','Excessive daytime sleepiness with cataplexy','Snoring with apnea','Leg movements only'],
      correct: 1,
      explanation: 'Narcolepsy = EDS plus cataplexy (sudden loss of muscle tone with emotion). Caused by hypocretin/orexin loss.',
    },
    {
      id: 'q-sleep-07',
      topic: 'sleep-pharm',
      course: 'rcp104',
      difficulty: 2,
      q: 'Modafinil and armodafinil are used for what indication?',
      choices: ['Insomnia','Excessive daytime sleepiness (narcolepsy, residual EDS in treated OSA, shift-work disorder)','RLS','Sleep paralysis'],
      correct: 1,
      explanation: 'Modafinil (Provigil) / armodafinil (Nuvigil) / solriamfetol are wake-promoting agents for residual EDS.',
    },
    {
      id: 'q-sleep-08',
      topic: 'sleep-pharm',
      course: 'rcp104',
      difficulty: 2,
      q: 'Which substances should patients with OSA avoid because they worsen upper-airway collapse and depress respiration?',
      choices: ['Caffeine and water','Alcohol, benzodiazepines, opioids, and barbiturates','Antihistamines only','ICS and SABA'],
      correct: 1,
      explanation: 'Alcohol, benzos, opioids, and barbiturates relax pharyngeal muscles and depress respiratory drive — avoid in OSA.',
    },
    {
      id: 'q-sleep-09',
      topic: 'sleep-pharm',
      course: 'rcp104',
      difficulty: 3,
      q: 'Insomnia differs from narcolepsy and OSA in that it primarily involves?',
      choices: ['Sleep-onset / maintenance difficulty despite adequate opportunity','Daytime cataplexy','Loud snoring with witnessed apneas','Urge to move the legs'],
      correct: 0,
      explanation: 'Insomnia = difficulty falling/staying asleep. Narcolepsy = EDS + cataplexy. OSA = airway collapse. RLS = leg urges.',
    },
    {
      id: 'q-sleep-10',
      topic: 'sleep-pharm',
      course: 'rcp104',
      difficulty: 3,
      q: 'Non-REM sleep is traditionally divided into stages 1–4. Which stages constitute "deep" slow-wave sleep?',
      choices: ['Stages 1–2','Stages 3–4','REM only','Stage 1 only'],
      correct: 1,
      explanation: 'N1–N2 are light non-REM; N3–N4 (now combined as N3) are deep slow-wave sleep. REM is separate.',
    },
  ];

  const groupTopics = ['nmba','diuretics','cns-drugs','opioids','benzos','vasopressors','antiarrhythmics','navel','antihypertensives','htn','mi-rx','sleep-pharm'];
  const existing = (window.ALL_QUESTIONS || []).filter(q => !(q.course === 'rcp104' && groupTopics.includes(q.topic)));
  window.ALL_QUESTIONS = existing.concat(additions);
})();
